import jsPDF from "jspdf";
import type { StopFullDetailsPayload } from "../redux/apis/distrubutor/routeViewApis";
import rabbitLogo from "../assets/Rabbit.svg";
import {
  formatApiDateMMDDYYYYDisplay,
  formatApiDateTimeMMDDYYYY,
  formatFullDetailsDateField,
} from "./formatApiDate";

export type WarehouseHeaderLine = {
  D_Name?: string;
  D_Addr1?: string;
  D_City?: string;
  D_State?: string;
  D_Phone?: string;
};

const PAGE_W = 210;
const PAGE_H = 297;
/** Tighter page margins — more content per page */
const M = 8;
/** Space reserved at bottom for footer + breathing room above it */
const FOOTER_ZONE = 20;
const GAP = 2;
const LINE_H = 3.15;
const RADIUS = 1.2;

/** Editorial palette */
const INK: [number, number, number] = [15, 23, 42];
const MUTED: [number, number, number] = [100, 116, 139];
const SLATE_BAR: [number, number, number] = [30, 41, 59];
const CARD_FILL: [number, number, number] = [248, 250, 252];
const CARD_STROKE: [number, number, number] = [226, 232, 240];
/** Rabbit.svg intrinsic size — must match raster + footer width/height ratio */
const RABBIT_SVG_W = 40;
const RABBIT_SVG_H = 33;
const RABBIT_ASPECT = RABBIT_SVG_W / RABBIT_SVG_H;

/** Medium image cells — two per row */
const CELL_GAP = 3;
const CELL_W = (PAGE_W - 2 * M - CELL_GAP) / 2;
const CELL_H = 54;
const INNER_PAD = 2.5;
const TITLE_BAR_H = 6;

/** Matches reference: full phrase, rabbit immediately after “Woopsa” */
const FOOTER_TEXT = "Report Generated by Woopsa";
/** Muted blue-grey text; rabbit reads slightly darker blue in asset */
const FOOTER_TEXT_RGB: [number, number, number] = [126, 142, 165];

/** Title line + at least one attachment row — avoid orphan "Attachments" heading */
const MIN_SPACE_ATTACHMENTS_BLOCK = 8 + CELL_H + CELL_GAP + 4;

function t(v: unknown): string {
  if (v == null || v === "") return "—";
  const s = String(v).trim();
  return s || "—";
}

function fmtBool(v: boolean | null | undefined): string {
  if (v === true) return "Yes";
  if (v === false) return "No";
  return "—";
}

function dwellMinutes(arrived: string | null | undefined, delivered: string | null | undefined): string {
  if (!arrived || !delivered) return "—";
  const a = Date.parse(arrived);
  const b = Date.parse(delivered);
  if (!Number.isFinite(a) || !Number.isFinite(b)) return "—";
  const m = Math.max(0, Math.round((b - a) / 60000));
  if (m < 60) return `${m} min`;
  const h = Math.floor(m / 60);
  const r = m % 60;
  return r ? `${h}h ${r}m` : `${h}h`;
}

function contentBottomY(): number {
  return PAGE_H - FOOTER_ZONE - M;
}

async function loadRabbitLogoDataUrl(): Promise<string | null> {
  try {
    const res = await fetch(rabbitLogo);
    if (!res.ok) return null;
    const svgText = await res.text();
    const svgBlob = new Blob([svgText], { type: "image/svg+xml;charset=utf-8" });
    const svgUrl = URL.createObjectURL(svgBlob);
    const img = await new Promise<HTMLImageElement>((resolve, reject) => {
      const i = new window.Image();
      i.onload = () => resolve(i);
      i.onerror = reject;
      i.src = svgUrl;
    });
    const iw = img.naturalWidth || RABBIT_SVG_W;
    const ih = img.naturalHeight || RABBIT_SVG_H;
    const canvas = document.createElement("canvas");
    /** Raster height in px; width follows SVG aspect so the PNG is not stretched */
    const outH = 132;
    const outW = Math.max(1, Math.round(outH * (iw / ih)));
    canvas.width = outW;
    canvas.height = outH;
    const ctx = canvas.getContext("2d");
    if (!ctx) return null;
    ctx.drawImage(img, 0, 0, outW, outH);
    URL.revokeObjectURL(svgUrl);
    return canvas.toDataURL("image/png");
  } catch {
    return null;
  }
}

async function urlToDataUrl(url: string): Promise<{ dataUrl: string; fmt: "PNG" | "JPEG" | "WEBP" } | null> {
  try {
    const res = await fetch(url, { mode: "cors" });
    if (!res.ok) return null;
    const blob = await res.blob();
    const mime = blob.type || "";
    let fmt: "PNG" | "JPEG" | "WEBP" = "JPEG";
    if (mime.includes("png")) fmt = "PNG";
    else if (mime.includes("webp")) fmt = "WEBP";
    const dataUrl = await new Promise<string | null>((resolve) => {
      const r = new FileReader();
      r.onloadend = () => resolve(typeof r.result === "string" ? r.result : null);
      r.onerror = () => resolve(null);
      r.readAsDataURL(blob);
    });
    if (!dataUrl) return null;
    return { dataUrl, fmt };
  } catch {
    return null;
  }
}

function drawFooterOnCurrentPage(doc: jsPDF, rabbitPng: string | null): void {
  const lineY = PAGE_H - FOOTER_ZONE;
  doc.setDrawColor(206, 212, 218);
  doc.setLineWidth(0.4);
  doc.line(M, lineY, PAGE_W - M, lineY);

  const baseY = PAGE_H - 6;
  const leftX = M + 2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...FOOTER_TEXT_RGB);

  doc.text(FOOTER_TEXT, leftX, baseY);
  let x = leftX + doc.getTextWidth(FOOTER_TEXT);

  /** Rabbit after “Woopsa”, same line — height ≈ cap height of 7.5pt text */
  const logoGapMm = 1.4;
  const logoH = 2.95;
  const logoW = logoH * RABBIT_ASPECT;

  if (rabbitPng) {
    try {
      x += logoGapMm;
      const logoY = baseY - logoH * 0.92;
      doc.addImage(rabbitPng, "PNG", x, logoY, logoW, logoH);
    } catch {
      /* ignore */
    }
  }

  doc.setTextColor(0, 0, 0);
}

function applyFootersAllPages(doc: jsPDF, rabbitPng: string | null): void {
  const n = doc.getNumberOfPages();
  for (let i = 1; i <= n; i++) {
    doc.setPage(i);
    drawFooterOnCurrentPage(doc, rabbitPng);
  }
}

type DocContext = {
  doc: jsPDF;
  warehouse: WarehouseHeaderLine | null;
  y: number;
};

function newPage(ctx: DocContext): void {
  ctx.doc.addPage();
  ctx.y = M;
}

/** Keep "Attachments" with its grid — not alone at the bottom of a page */
function ensureAttachmentsSectionStart(ctx: DocContext): void {
  if (contentBottomY() - ctx.y < MIN_SPACE_ATTACHMENTS_BLOCK) {
    newPage(ctx);
  }
}

function ensureY(ctx: DocContext, needMm: number): void {
  if (ctx.y + needMm > contentBottomY()) {
    newPage(ctx);
  }
}

function drawWarehouseHeaderRich(ctx: DocContext, title: string): void {
  const { doc, warehouse } = ctx;
  const boxTop = ctx.y;

  const addr = warehouse
    ? [warehouse.D_Addr1, [warehouse.D_City, warehouse.D_State].filter(Boolean).join(", ")].filter(Boolean).join(" · ")
    : "";
  /** First segment includes top padding inside card + title line + gap (title baseline moved down for visible top pad) */
  let h = 10 + 7 + 2;
  if (warehouse?.D_Name) h += LINE_H;
  if (addr.trim()) {
    const lines = doc.splitTextToSize(addr, PAGE_W - 2 * M - 8);
    h += lines.length * LINE_H;
  }
  if (warehouse?.D_Phone) h += LINE_H;
  h += 3;

  doc.setFillColor(...CARD_FILL);
  doc.setDrawColor(...CARD_STROKE);
  doc.setLineWidth(0.25);
  doc.roundedRect(M, boxTop, PAGE_W - 2 * M, h, RADIUS, RADIUS, "FD");

  /** jsPDF uses baseline Y; 13pt title needs room above baseline so glyphs stay inside the card */
  const titleBaselineMm = boxTop + 8.5;
  let innerY = titleBaselineMm;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...INK);
  doc.text(title, M + 4, innerY);
  innerY += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  if (warehouse) {
    if (warehouse.D_Name) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(51, 65, 85);
      doc.text(warehouse.D_Name, M + 4, innerY);
      doc.setFont("helvetica", "normal");
      innerY += LINE_H;
    }
    if (addr.trim()) {
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      const lines = doc.splitTextToSize(addr, PAGE_W - 2 * M - 8);
      doc.text(lines, M + 4, innerY);
      innerY += lines.length * LINE_H;
    }
    if (warehouse.D_Phone) {
      doc.text(`Phone  ${warehouse.D_Phone}`, M + 4, innerY);
    }
  }
  ctx.y = boxTop + h + GAP + 1;
  doc.setTextColor(0, 0, 0);
}

function startSection(ctx: DocContext, name: string): void {
  ensureY(ctx, 12);
  const { doc } = ctx;
  const barH = 6;
  doc.setFillColor(...SLATE_BAR);
  doc.roundedRect(M, ctx.y, PAGE_W - 2 * M, barH, 0.8, 0.8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(name.toUpperCase(), M + 3.5, ctx.y + 4.2);
  ctx.y += barH + 2;
  doc.setTextColor(0, 0, 0);
}

function stackedFieldHeight(doc: jsPDF, colW: number, row: { label: string; value: string }): number {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  const lines = doc.splitTextToSize(row.value, colW - 1.5);
  return 2.4 + 3.2 + Math.max(0, lines.length - 1) * LINE_H;
}

function drawStackedField(
  doc: jsPDF,
  x: number,
  y: number,
  colW: number,
  row: { label: string; value: string }
): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...MUTED);
  doc.text(row.label, x, y + 2.4);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...INK);
  const lines = doc.splitTextToSize(row.value, colW - 1.5);
  doc.text(lines, x, y + 5.6);
  return stackedFieldHeight(doc, colW, row);
}

function drawKvCardTwoColumn(ctx: DocContext, rows: Array<{ label: string; value: string }>): void {
  const { doc } = ctx;
  const pad = 3.5;
  const gutter = 4;
  const innerW = PAGE_W - 2 * M - 2 * pad;
  const colW = (innerW - gutter) / 2;

  let totalInner = pad;
  for (let i = 0; i < rows.length; i += 2) {
    const rowA = rows[i];
    const rowB = rows[i + 1];
    const ha = stackedFieldHeight(doc, colW, rowA);
    const hb = rowB ? stackedFieldHeight(doc, colW, rowB) : 0;
    totalInner += Math.max(ha, hb || 0);
    if (i + 2 < rows.length) totalInner += 1.8;
  }
  totalInner += pad;

  ensureY(ctx, totalInner + 4);
  const top = ctx.y;
  doc.setFillColor(...CARD_FILL);
  doc.setDrawColor(...CARD_STROKE);
  doc.setLineWidth(0.25);
  doc.roundedRect(M, top, PAGE_W - 2 * M, totalInner, RADIUS, RADIUS, "FD");

  let cy = top + pad;
  for (let i = 0; i < rows.length; i += 2) {
    const rowA = rows[i];
    const rowB = rows[i + 1];
    const ha = drawStackedField(doc, M + pad, cy, colW, rowA);
    const hb = rowB ? drawStackedField(doc, M + pad + colW + gutter, cy, colW, rowB) : 0;
    cy += Math.max(ha, hb || 0);
    if (i + 2 < rows.length) cy += 1.8;
  }

  ctx.y = top + totalInner + GAP;
}

const FULL_W = PAGE_W - 2 * M;

async function drawImageCell(
  ctx: DocContext,
  x: number,
  yTop: number,
  cellW: number,
  label: string,
  url: string | null
): Promise<void> {
  const { doc } = ctx;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(...CARD_STROKE);
  doc.setLineWidth(0.25);
  doc.roundedRect(x, yTop, cellW, CELL_H, RADIUS, RADIUS, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text(label, x + INNER_PAD, yTop + 5);

  const imgTop = yTop + TITLE_BAR_H;
  const imgW = cellW - 2 * INNER_PAD;
  const imgH = CELL_H - TITLE_BAR_H - 2 * INNER_PAD;
  const cx = x + cellW / 2;

  if (!url || !String(url).trim()) {
    doc.setFillColor(248, 249, 250);
    doc.setDrawColor(206, 212, 218);
    doc.setLineWidth(0.25);
    doc.roundedRect(x + INNER_PAD, imgTop, imgW, imgH, 0.8, 0.8, "FD");
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(145, 153, 159);
    doc.text("No image", cx, imgTop + imgH / 2 + 1, { align: "center" });
    doc.setTextColor(0, 0, 0);
    return;
  }

  const loaded = await urlToDataUrl(url);
  if (!loaded) {
    doc.setFillColor(255, 245, 245);
    doc.setDrawColor(248, 215, 218);
    doc.roundedRect(x + INNER_PAD, imgTop, imgW, imgH, 0.8, 0.8, "FD");
    doc.setFont("helvetica", "italic");
    doc.setFontSize(7);
    doc.setTextColor(220, 53, 69);
    doc.text("Could not load", cx, imgTop + imgH / 2, { align: "center" });
    doc.setTextColor(0, 0, 0);
    return;
  }

  try {
    const img = new window.Image();
    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = () => reject();
      img.src = loaded.dataUrl;
    });
    const iw = img.width;
    const ih = img.height;
    if (!iw || !ih) return;
    let wMm = imgW;
    let hMm = (ih / iw) * wMm;
    if (hMm > imgH) {
      hMm = imgH;
      wMm = (iw / ih) * hMm;
    }
    const ix = x + INNER_PAD + (imgW - wMm) / 2;
    const iy = imgTop + (imgH - hMm) / 2;
    doc.addImage(loaded.dataUrl, loaded.fmt, ix, iy, wMm, hMm);
  } catch {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(7);
    doc.setTextColor(220, 53, 69);
    doc.text("Unavailable", cx, imgTop + imgH / 2, { align: "center" });
    doc.setTextColor(0, 0, 0);
  }
}

async function drawImageCellHalf(ctx: DocContext, x: number, yTop: number, label: string, url: string | null): Promise<void> {
  await drawImageCell(ctx, x, yTop, CELL_W, label, url);
}

async function drawImageCellFull(ctx: DocContext, yTop: number, label: string, url: string | null): Promise<void> {
  await drawImageCell(ctx, M, yTop, FULL_W, label, url);
}

async function drawImageGrid(ctx: DocContext, slots: Array<{ label: string; url: string | null }>): Promise<void> {
  let i = 0;
  while (i < slots.length) {
    if (slots.length - i === 1) {
      ensureY(ctx, CELL_H + GAP);
      await drawImageCellFull(ctx, ctx.y, slots[i].label, slots[i].url);
      ctx.y += CELL_H + GAP;
      break;
    }
    ensureY(ctx, CELL_H + GAP);
    await drawImageCellHalf(ctx, M, ctx.y, slots[i].label, slots[i].url);
    await drawImageCellHalf(ctx, M + CELL_W + CELL_GAP, ctx.y, slots[i + 1].label, slots[i + 1].url);
    ctx.y += CELL_H + GAP;
    i += 2;
  }
}

async function renderDeliveredStopPodPdfBody(ctx: DocContext, data: StopFullDetailsPayload): Promise<void> {
  const { stop, customer, deliveryPODs } = data;

  drawWarehouseHeaderRich(ctx, "Delivery confirmation");

  const stopRows = [
    { label: "Route", value: t(stop.routeName) },
    { label: "Service day", value: formatApiDateMMDDYYYYDisplay(stop.day) },
    { label: "Stop #", value: t(stop.stopSequence) },
    { label: "Order", value: t(stop.orderNumber) },
    { label: "Customer #", value: t(stop.C_Number) },
    { label: "Route started", value: fmtBool(stop.routeStarted) },
    { label: "Last stop", value: fmtBool(stop.isLastStop) },
    { label: "Distance", value: `${t(stop.totalKilometers)} km` },
    { label: "Invoice amount", value: stop.invoiceAmount != null ? String(stop.invoiceAmount) : "—" },
    ...(stop.invoiceUrl ? [{ label: "Invoice URL", value: t(stop.invoiceUrl) }] : []),
    ...(stop.notes && String(stop.notes).trim() ? [{ label: "Notes", value: t(stop.notes) }] : []),
    { label: "Arrived", value: formatApiDateTimeMMDDYYYY(stop.arrivedAt) },
    { label: "Delivered", value: formatApiDateTimeMMDDYYYY(stop.deliveredAt) },
    { label: "Time at stop", value: dwellMinutes(stop.arrivedAt, stop.deliveredAt) },
    { label: "GPS stop", value: `${t(stop.latitude)}, ${t(stop.longitude)}` },
    { label: "Approach", value: `${t(stop.startLatitude)}, ${t(stop.startLongitude)}` },
    { label: "Depart", value: `${t(stop.endLatitude)}, ${t(stop.endLongitude)}` },
  ];

  startSection(ctx, "Route & stop");
  drawKvCardTwoColumn(ctx, stopRows);

  if (
    stop.reSchedule ||
    stop.reScheduleDate ||
    stop.reScheduleTime ||
    (stop.reScheduleReason && String(stop.reScheduleReason).trim())
  ) {
    startSection(ctx, "Reschedule");
    drawKvCardTwoColumn(ctx, [
      { label: "Active", value: fmtBool(stop.reSchedule) },
      { label: "Date", value: formatFullDetailsDateField(stop.reScheduleDate) },
      { label: "Time", value: t(stop.reScheduleTime) },
      { label: "Reason", value: t(stop.reScheduleReason) },
      ...(stop.reScheduleNotes && String(stop.reScheduleNotes).trim()
        ? [{ label: "Detail", value: t(stop.reScheduleNotes) }]
        : []),
    ]);
  }

  startSection(ctx, "Customer");
  drawKvCardTwoColumn(ctx, [
    { label: "Name", value: t(customer.C_Name) },
    { label: "Address", value: t(customer.address) },
    { label: "ZIP", value: t(customer.zip) },
    { label: "Phone", value: t(customer.phone) },
    { label: "Email", value: t(customer.email) },
  ]);

  const pods = Array.isArray(deliveryPODs) ? deliveryPODs : [];
  for (let pi = 0; pi < pods.length; pi++) {
    const pod = pods[pi];
    startSection(ctx, pods.length > 1 ? `Proof of delivery · ${pi + 1} / ${pods.length}` : "Proof of delivery");
    drawKvCardTwoColumn(ctx, [
      { label: "Amount", value: pod.amount != null ? String(pod.amount) : "—" },
      { label: "Payment terms", value: t(pod.paymentTerms) },
      { label: "Terms complete", value: fmtBool(pod.paymentTermComplete) },
      { label: "Post-delivery", value: fmtBool(pod.postDeliveryCompleted) },
      { label: "Bundles", value: `${t(pod.scannedBundles)} / ${t(pod.expectedBundles)}` },
      { label: "All scanned", value: fmtBool(pod.allBundlesScanned) },
      { label: "Paid by check", value: fmtBool(pod.paymentInCheck) },
      ...(pod.paymentInCheck && pod.checkNumber ? [{ label: "Check #", value: t(pod.checkNumber) }] : []),
      { label: "Signed by", value: t(pod.signBy) },
      { label: "Captured", value: formatApiDateTimeMMDDYYYY(pod.podAt) },
      ...(pod.invoiceAmount != null && pod.invoiceAmount !== 0 ? [{ label: "POD invoice", value: String(pod.invoiceAmount) }] : []),
      ...(pod.invoiceMessage && String(pod.invoiceMessage).trim() ? [{ label: "Invoice note", value: t(pod.invoiceMessage) }] : []),
      ...(pod.notes && String(pod.notes).trim() ? [{ label: "Driver notes", value: t(pod.notes) }] : []),
      ...(() => {
        const boxN = Array.isArray(pod.boxBarCode) ? pod.boxBarCode.length : 0;
        const scanN = Array.isArray(pod.scanBarCode) ? pod.scanBarCode.length : 0;
        return boxN || scanN ? [{ label: "Barcodes", value: `Box ${boxN} · Scan ${scanN}` }] : [];
      })(),
    ]);

    const photos = (Array.isArray(pod.photos) ? pod.photos : []).filter(
      (u): u is string => typeof u === "string" && u.trim().length > 0
    );
    const photoSlots = photos.map((u, i) => ({ label: `Delivery photo ${i + 1}`, url: u }));

    const slots: Array<{ label: string; url: string | null }> = [
      { label: "Customer signature", url: pod.customerSignature },
      { label: "Check (front)", url: pod.checkImage },
      { label: "Check (additional)", url: pod.checkImage1 },
      ...photoSlots,
    ];

    ensureAttachmentsSectionStart(ctx);
    ctx.doc.setFont("helvetica", "bold");
    ctx.doc.setFontSize(8);
    ctx.doc.setTextColor(...MUTED);
    ctx.doc.text("Attachments", M + 1, ctx.y + 3.5);
    ctx.doc.setDrawColor(...CARD_STROKE);
    ctx.doc.setLineWidth(0.2);
    ctx.doc.line(M, ctx.y + 5.2, PAGE_W - M, ctx.y + 5.2);
    ctx.y += 7;
    ctx.doc.setTextColor(0, 0, 0);

    await drawImageGrid(ctx, slots);
  }
}

export async function downloadDeliveredStopPodPdf(data: StopFullDetailsPayload, warehouse: WarehouseHeaderLine | null): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const rabbitPng = await loadRabbitLogoDataUrl();

  const ctx: DocContext = {
    doc,
    warehouse,
    y: M,
  };

  await renderDeliveredStopPodPdfBody(ctx, data);

  applyFootersAllPages(doc, rabbitPng);

  const safeRoute = String(data.stop.routeName ?? "route").replace(/[^\w.-]+/g, "_");
  const fname = `Delivery-${safeRoute}-order-${data.stop.orderNumber}.pdf`;
  doc.save(fname);
}

/** One PDF page per stop; same layout as single-stop PDF */
export async function downloadRouteFullStopsPodPdf(
  stops: StopFullDetailsPayload[],
  warehouse: WarehouseHeaderLine | null
): Promise<void> {
  if (!stops.length) return;
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const rabbitPng = await loadRabbitLogoDataUrl();

  for (let i = 0; i < stops.length; i++) {
    if (i > 0) doc.addPage();
    const ctx: DocContext = { doc, warehouse, y: M };
    await renderDeliveredStopPodPdfBody(ctx, stops[i]);
  }

  applyFootersAllPages(doc, rabbitPng);

  const first = stops[0].stop;
  const safeRoute = String(first.routeName ?? "route").replace(/[^\w.-]+/g, "_");
  doc.save(`Delivery-${safeRoute}-route-all-stops.pdf`);
}
