import jsPDF from 'jspdf';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const jspdfAutoTable = require('jspdf-autotable');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const JsBarcode = require('jsbarcode');
// eslint-disable-next-line @typescript-eslint/no-require-imports
import rabbitLogo from '../assets/Rabbit.svg';
import { getContactUsData } from '../redux/apis/landingPageApis';

// Column keys and labels (must match InvoiceTemplateTab). Total PPD, Price w/t without PPD, Extended total, Price w/t with PPD are frontend-calculated only (not from backend).
// Formulas: Prepaid tax amount = per unit from API; Total PPD = prepaidTaxAmount * qty; Price w/t with PPD = price + OTP + prepaidTaxAmount; Price w/t without PPD = price + OTP; Extended total = chosen price w/t * qty.
const INVOICE_COLUMN_FIELDS = [
  { key: 'orderQty', label: 'qty' },
  { key: 'shippedQty', label: 'Shipped' },
  { key: 'itemNumber', label: 'Item #' },
  { key: 'description', label: 'Description' },
  { key: 'pack', label: 'Pack' },
  { key: 'size', label: 'Size' },
  { key: 'upc', label: 'UPC' },
  { key: 'sortNumber', label: 'Short #' },
  { key: 'ebt', label: 'EBT' },
  { key: 'retail1', label: 'SRP' },
  { key: 'deposit', label: 'Deposit' },
  { key: 'price', label: 'Price' },
  { key: 'unitPrice', label: 'Unit price' },
  { key: 'tax', label: 'Tax' },
  { key: 'prepaidTaxAmount', label: 'Prepaid tax amount' },
  { key: 'totalPPD', label: 'Total PPD' },
  { key: 'priceWithTaxWithPPD', label: 'EXT Price with PPD' },
  { key: 'priceWithTaxWithoutPPD', label: 'EXT Price without PPD' },
  { key: 'extendedTotal', label: 'Extended total' },
];

/** Return selected column keys in display order: default = fixed order; custom = by columnOrder (1-based). */
function getOrderedSelectedKeys(
  template: InvoiceTemplateConfig
): string[] {
  const selected = INVOICE_COLUMN_FIELDS.filter((f) => template.selectedColumns[f.key]).map((f) => f.key);
  if (template.columnPlacement !== 'custom' || !template.columnOrder || Object.keys(template.columnOrder).length === 0) {
    return selected;
  }
  return selected.sort((a, b) => (template.columnOrder![a] ?? 999) - (template.columnOrder![b] ?? 999));
}

const SUMMARY_HEADER_HEIGHT_MM = 28;
/** Height reserved for "Report generated by Woopsa" line on last page only. */
const WOOPSA_FOOTER_HEIGHT_MM = 10;
/** Bottom margin on non-last pages (no footer/Woopsa on these pages). */
const NON_LAST_PAGE_BOTTOM_MM = 10;
/** Reserved at bottom on last page: footer block (25% summary + 75% msg) + category summary + Woopsa line. */
const LAST_PAGE_FOOTER_BLOCK_MM = 48;
const LAST_PAGE_CATEGORY_SUMMARY_MM = 28;
/** Minimal gap from page bottom so "Report generated by Woopsa" sits at bottom. */
const WOOPSA_LINE_BOTTOM_MM = 2;
/** Bottom margin so last page has room: QTY Category table + gap + footer block + Woopsa line. */
function getTableBottomMarginMM(template: InvoiceTemplateConfig): number {
  const footerAndWoopsa = LAST_PAGE_FOOTER_BLOCK_MM + 1 + WOOPSA_LINE_BOTTOM_MM; // 1mm gap between footer block and Woopsa line
  const withCategorySummary = LAST_PAGE_CATEGORY_SUMMARY_MM + GAP_CATEGORY_TO_FOOTER_MM + footerAndWoopsa;
  return Math.max(withCategorySummary, template.showReportGeneratedByWoopsa ? WOOPSA_FOOTER_HEIGHT_MM : 6);
}

const ROW_HEIGHT_EST_MM = 5;
const GROUP_HEADER_EST_MM = 8;
const SUBTOTAL_ROW_EST_MM = 5;

/** Estimate total page count when using big bottom margin on last page only (for per-page margin). */
function estimateTotalPages(
  grouped: Array<{ key: string; label?: string; items: InvoiceLineItem[] }>,
  template: InvoiceTemplateConfig,
  headerHeight: number,
  tableMarginTopNewPages: number,
  pageHeight: number,
  tableBottomMarginMM: number
): number {
  let pages = 1;
  let y = headerHeight + 2;
  const minYLast = pageHeight - tableBottomMarginMM;
  const showGroupSubtotal =
    template.groupBy === 'alphabetSalesCategory' || template.groupBy === 'sequence';
  const hasGroupHeader =
    (template.groupBy === 'alphabetSalesCategory' && template.showGroupHeader) ||
    (template.groupBy === 'sequence' && template.showGroupHeader);

  grouped.forEach((group, groupIdx) => {
    if (groupIdx > 0) y += 4;
    if (hasGroupHeader) {
      if (y + GROUP_HEADER_EST_MM > minYLast) {
        pages += 1;
        y = tableMarginTopNewPages + 2;
      }
      y += GROUP_HEADER_EST_MM;
    }
    const rowsH = group.items.length * ROW_HEIGHT_EST_MM;
    if (y + rowsH > minYLast) {
      let remaining = rowsH;
      while (remaining > 0) {
        const space = minYLast - y;
        if (space <= 0) {
          pages += 1;
          y = tableMarginTopNewPages + 2;
          continue;
        }
        const rowsFit = Math.floor(space / ROW_HEIGHT_EST_MM);
        remaining -= rowsFit * ROW_HEIGHT_EST_MM;
        if (remaining > 0) {
          pages += 1;
          y = tableMarginTopNewPages + 2;
        } else {
          y += rowsFit * ROW_HEIGHT_EST_MM;
        }
      }
    } else {
      y += rowsH;
    }
    if (showGroupSubtotal) {
      if (y + SUBTOTAL_ROW_EST_MM > minYLast) {
        pages += 1;
        y = tableMarginTopNewPages + 2;
      }
      y += SUBTOTAL_ROW_EST_MM + 4;
    } else {
      y += 4;
    }
  });
  return pages;
}
/** Gap (mm) between QTY CATEGORY table and the footer block on the last page. */
const GAP_CATEGORY_TO_FOOTER_MM = 10;
/** Approximate height (mm) per row in QTY CATEGORY table for overlap check. */
const CATEGORY_TABLE_ROW_HEIGHT_MM = 6;
/** Fixed width (mm) for Description column so it stays the same across pages and invoices. */
const DESCRIPTION_COLUMN_WIDTH_MM = 50;

export type InvoiceGroupBy = 'alphabetSalesCategory' | 'alphabet' | 'sequence' | '';
export type HeaderPageOption = 'all' | 'first' | 'firstPlusSummary';
export type FooterLayoutOption = 'messageLeft' | 'messageRight';
export type LogoPosition = 'left' | 'center' | 'right';

/** Normalize API string values that may come as lowercase (e.g. alphabetsalescategory) to expected option values. */
function normalizeGroupBy(value: string | undefined): InvoiceGroupBy {
  if (!value) return 'alphabetSalesCategory';
  const v = value.toLowerCase();
  if (v === 'alphabetsalescategory') return 'alphabetSalesCategory';
  if (v === 'alphabet') return 'alphabet';
  if (v === 'sequence') return 'sequence';
  return value as InvoiceGroupBy;
}

function normalizeHeaderOnPages(value: string | undefined): HeaderPageOption {
  if (!value) return 'first';
  const v = value.toLowerCase();
  if (v === 'firstplussummary') return 'firstPlusSummary';
  if (v === 'first') return 'first';
  if (v === 'all') return 'all';
  return 'first' as HeaderPageOption;
}

function normalizeFooterLayout(value: string | undefined): FooterLayoutOption {
  if (!value) return 'messageLeft';
  const v = value.toLowerCase();
  if (v === 'messageright') return 'messageRight';
  if (v === 'messageleft') return 'messageLeft';
  return value as FooterLayoutOption;
}

function normalizeLogoPosition(value: string | undefined): LogoPosition {
  if (!value) return 'center';
  const v = value.toLowerCase();
  if (v === 'left') return 'left';
  if (v === 'center') return 'center';
  if (v === 'right') return 'right';
  return value as LogoPosition;
}

/** Template config for invoice PDF (compatible with manager API InvoiceTemplateApi). */
export interface InvoiceTemplateConfig {
  groupBy: InvoiceGroupBy;
  showGroupHeader: boolean;
  selectedColumns: Record<string, boolean>;
  /** 'default' = fixed column order; 'custom' = use columnOrder */
  columnPlacement?: 'default' | 'custom';
  /** When columnPlacement is 'custom': field key -> 1-based column position */
  columnOrder?: Record<string, number>;
  /** Extended total column = (Price w/t with PPD * qty) or (Price w/t without PPD * qty) */
  extendedTotalBasedOn?: 'withPPD' | 'withoutPPD';
  upcOption: string;
  showDistributorDetails: boolean;
  showCustomerDetails: boolean;
  showBillTo: boolean;
  showShipTo: boolean;
  showDocNumber: boolean;
  showPageOf: boolean;
  showInvoiceDate: boolean;
  showInvoiceDateWithTime: boolean;
  showRoute: boolean;
  showStop: boolean;
  showLogo: boolean;
  logoPosition: LogoPosition;
  showTerms: boolean;
  headerOnPages: HeaderPageOption;
  showHeaderMessage: boolean;
  headerMessageFirstPage: string;
  footerLayout: FooterLayoutOption;
  showFooterMessage: boolean;
  footerMessageLastPage: string;
  showSubTotal: boolean;
  showDeliveryCharge: boolean;
  showDeposit: boolean;
  showHouseCharge: boolean;
  showPosCheck: boolean;
  showPosCash: boolean;
  showPosCredit: boolean;
  showLastBalance: boolean;
  showTotalAmountDue: boolean;
  showReportGeneratedByWoopsa: boolean;
  /** Custom labels for footer summary lines (netInvoice, totalPPD, deliveryCharge, deposit, houseCharge, posCheck, posCash, posCredit, invoiceTotal, lastBalance, totalDue). */
  footerSummaryLabels?: Record<string, string>;
  /** Custom column header labels (column key -> display label), e.g. { orderQty: "Quantity", itemNumber: "Item" }. */
  columnHeaderNames?: Record<string, string>;
}

/** One line item on the invoice. */
export interface InvoiceLineItem {
  orderQty: number;
  shippedQty: number;
  description: string;
  /** When true, show "*This item was out of stock" below description in same cell (small font). */
  outOfStockNote?: boolean;
  itemNumber: string | number;
  sortNumber: number;
  upc: string;
  pack?: string | number;
  size?: string | number;
  deposit?: number;
  price: number;
  /** Unit price from API (inventory.Unit_Price); used for "Unit price" column. */
  unitPrice?: number;
  tax: number;
  /** Per-unit prepaid tax amount. */
  prepaidTaxAmount?: number;
  priceWithTax: number;
  /** Price with tax including prepaid (same as priceWithTax when PPD present). */
  priceWithTaxWithPPD?: number;
  /** Price with tax excluding prepaid (price + state tax only). */
  priceWithTaxWithoutPPD?: number;
  totalPrice: number;
  retail1: number;
  ebt: boolean;
  salesCategory?: string;
}

/** Bill To / Ship To display (same key names as customer). */
export interface BillToShipToInfo {
  name: string;
  address: string;
  phone?: string;
}

/** Order data passed to invoice PDF generator (like PicklistOrderData for picklist). */
export interface InvoiceOrderData {
  customer: { number: number; name: string; address: string; route?: number; stop?: number; phone?: string; state?: string };
  /** When set, Bill To uses this; otherwise Bill To = customer (same as Ship To). */
  billTo?: BillToShipToInfo;
  distributor: { name: string; address?: string; orderLine?: string; phoneFax?: string; whatsapp?: string };
  invoiceNumber: string;
  orderNumber: string;
  orderDate: string;
  invoiceDate: string;
  items: InvoiceLineItem[];
  salesPerson?: string;
  customerLicense?: string;
  termsCode?: number;
  via?: string;
  totals: {
    subTotal?: number;
    deliveryCharge?: number;
    deposit?: number;
    lastBalance?: number;
    invoiceTotal?: number;
    totalAmountDue?: number;
    totalPrepaidTax?: number;
    houseCharge?: number;
    posCheck?: number;
    posCash?: number;
    posCredit?: number;
  };
}

const generateBarcodeDataUrl = (text: string): string | null => {
  try {
    const canvas = document.createElement('canvas');
    JsBarcode(canvas, text, { format: 'CODE128', width: 2, height: 40, displayValue: false, margin: 2 });
    return canvas.toDataURL('image/png');
  } catch {
    return null;
  }
};

/** Load image from URL and return as data URL (for Contact Us logo). */
const loadLogoFromUrl = (url: string): Promise<string | null> => {
  return new Promise<string | null>((resolve) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        if (ctx) {
          canvas.width = img.width || 40;
          canvas.height = img.height || 33;
          ctx.drawImage(img, 0, 0);
          resolve(canvas.toDataURL('image/png'));
        } else resolve(null);
      } catch {
        resolve(null);
      }
    };
    img.onerror = () => resolve(null);
    img.src = url;
  });
};

/** Load Woopsa Rabbit logo as data URL for "Report generated by Woopsa" footer. */
const loadRabbitLogoAsDataUrl = async (): Promise<string | null> => {
  const logoPath = typeof rabbitLogo === 'string' ? rabbitLogo : (rabbitLogo as string);
  try {
    const dataUrl = await loadLogoFromUrl(logoPath);
    if (dataUrl) return dataUrl;
    const fetchUrl = logoPath.startsWith('data:') || logoPath.startsWith('http') ? logoPath : (logoPath.startsWith('/') ? logoPath : `/${logoPath}`);
    const response = await fetch(fetchUrl);
    if (!response.ok) return null;
    const blob = await response.blob();
    return new Promise<string | null>((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(typeof reader.result === 'string' ? reader.result : null);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
};

const formatCurrency = (n: number): string => (n != null && !Number.isNaN(n) ? `$${Number(n).toFixed(2)}` : '$0.00');

/** Format date string (ISO or YYYY-MM-DD) to MM/DD/YYYY for display. */
const formatInvoiceDate = (dateStr: string): string => {
  if (!dateStr || typeof dateStr !== 'string') return '';
  const trimmed = dateStr.trim().split('T')[0];
  const match = trimmed.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (match) return `${match[2]}/${match[3]}/${match[1]}`;
  return dateStr;
};

const descriptionSortOrder = (a: string, b: string): number => {
  const cat = (ch: string): number => {
    if (ch === ' ' || ch === '') return 0;
    if (/[0-9]/.test(ch)) return 2;
    if (/[A-Za-z]/.test(ch)) return 3;
    return 1;
  };
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const ca = a[i] ?? '';
    const cb = b[i] ?? '';
    const diff = cat(ca) - cat(cb);
    if (diff !== 0) return diff;
    if (ca !== cb) return ca.localeCompare(cb, undefined, { numeric: true });
  }
  return 0;
};

function groupInvoiceItems(
  template: InvoiceTemplateConfig,
  items: InvoiceLineItem[]
): Array<{ key: string; label?: string; items: InvoiceLineItem[] }> {
  const groupBy = template.groupBy;
  const showGroupHeader = template.showGroupHeader;
  if (!groupBy) return [{ key: 'all', items: [...items].sort((a, b) => a.sortNumber - b.sortNumber) }];
  if (groupBy === 'sequence') {
    const map: Record<string, InvoiceLineItem[]> = {};
    items.forEach((item) => {
      const k = String(item.sortNumber);
      if (!map[k]) map[k] = [];
      map[k].push(item);
    });
    return Object.keys(map)
      .sort((a, b) => Number(a) - Number(b))
      .map((key) => ({ key, items: map[key] }));
  }
  if (groupBy === 'alphabet') {
    const sorted = [...items].sort((a, b) =>
      descriptionSortOrder((a.description || '').trim(), (b.description || '').trim())
    );
    return [{ key: 'all', items: sorted }];
  }
  if (groupBy === 'alphabetSalesCategory') {
    const byCat: Record<string, InvoiceLineItem[]> = {};
    items.forEach((item) => {
      const cat = item.salesCategory || 'Other';
      if (!byCat[cat]) byCat[cat] = [];
      byCat[cat].push(item);
    });
    const result: Array<{ key: string; label?: string; items: InvoiceLineItem[] }> = [];
    Object.keys(byCat)
      .sort()
      .forEach((cat) => {
        const list = byCat[cat].sort((a, b) =>
          descriptionSortOrder((a.description || '').trim(), (b.description || '').trim())
        );
        if (showGroupHeader) result.push({ key: cat, label: cat, items: list });
        else result.push({ key: cat, items: list });
      });
    return result;
  }
  return [{ key: 'all', items: [...items].sort((a, b) => a.sortNumber - b.sortNumber) }];
}

/** Draw header tables on the right: 3 rows only (reduced size). Returns bottom Y. */
function drawHeaderTables(
  doc: jsPDF,
  orderData: InvoiceOrderData,
  template: InvoiceTemplateConfig,
  startX: number,
  startY: number,
  tableWidth: number,
  pageWidth: number,
  pageMargin: number
): number {
  const cust = orderData.customer;
  const formatDate = (): string => formatInvoiceDate(orderData.invoiceDate || orderData.orderDate || '');
  const autoTableFn = jspdfAutoTable.default || jspdfAutoTable.autoTable || jspdfAutoTable;
  const greyHead = { fillColor: [200, 200, 200] as [number, number, number], textColor: [0, 0, 0], fontStyle: 'normal', fontSize: 5 };
  const cellW3 = tableWidth / 3;
  const tableMargin = { left: startX, right: pageMargin };
  const tableStyle = { fontSize: 5, cellPadding: 1 };

  // Row 1: CUSTOMER NO | INVOICE# | INVOICE DATE
  autoTableFn(doc, {
    startY,
    head: [['CUSTOMER NO', 'INVOICE#:', 'INVOICE DATE:']],
    body: [[String(cust.number), orderData.invoiceNumber, formatDate()]],
    columnStyles: { 0: { cellWidth: cellW3 }, 1: { cellWidth: cellW3 }, 2: { cellWidth: cellW3 } },
    styles: tableStyle,
    headStyles: greyHead,
    margin: tableMargin,
    tableWidth,
  });
  let y = (doc as any).lastAutoTable.finalY + 0.5;

  // Row 2: TERMS | CUSTOMER LICENCE# | Delivery Via (from orderData.via = Delivery_Description when present)
  const termsText = orderData.termsCode != null ? String(orderData.termsCode) : '';
  const licenseText = (orderData.customerLicense ?? '').trim() ? orderData.customerLicense! : '-';
  const viaText = (orderData.via ?? '').trim() || '-';
  autoTableFn(doc, {
    startY: y,
    head: [['TERMS:', 'CUSTOMER LICENCE#', 'Delivery Via']],
    body: [[termsText || '-', `${licenseText}`, viaText]],
    columnStyles: { 0: { cellWidth: cellW3 }, 1: { cellWidth: cellW3 }, 2: { cellWidth: cellW3 } },
    styles: tableStyle,
    headStyles: greyHead,
    margin: tableMargin,
    tableWidth,
  });
  y = (doc as any).lastAutoTable.finalY + 0.5;

  // Row 3: SALES PERSON | ROUTE NUMBER | STOP NUMBER (from orderData when present)
  const salesPersonText = (orderData.salesPerson ?? '').trim() || '-';
  const routeText = template.showRoute ? String(cust.route ?? '') : '';
  const stopText = template.showStop ? String(cust.stop ?? '') : '';
  autoTableFn(doc, {
    startY: y,
    head: [['SALES PERSON', 'ROUTE NUMBER', 'STOP NUMBER']],
    body: [[salesPersonText, routeText, stopText]],
    columnStyles: { 0: { cellWidth: cellW3 }, 1: { cellWidth: cellW3 }, 2: { cellWidth: cellW3 } },
    styles: tableStyle,
    headStyles: greyHead,
    margin: tableMargin,
    tableWidth,
  });
  return (doc as any).lastAutoTable.finalY;
}

const BILL_SHIP_HEADER_COLOR = [70, 70, 90] as [number, number, number];

/** Draw BILL TO / SHIP TO as one table. Bill To uses orderData.billTo when present, else customer (same as Ship To). Returns bottom Y. */
function drawBillToShipTo(
  doc: jsPDF,
  orderData: InvoiceOrderData,
  template: InvoiceTemplateConfig,
  startY: number,
  leftX: number,
  pageWidth: number,
  margin: number
): number {
  if (!template.showCustomerDetails || (!template.showBillTo && !template.showShipTo)) return startY;
  const cust = orderData.customer;
  const shipToLines: string[] = [cust.name || ''];
  const shipAddr = (cust.address || '').trim();
  if (shipAddr) shipAddr.split(',').map((p) => p.trim()).filter(Boolean).forEach((p) => shipToLines.push(p));
  if (cust.phone) shipToLines.push(`PHONE: ${cust.phone}`);
  const shipToContent = shipToLines.join('\n');
  const billToSource = orderData.billTo ?? cust;
  const billToLines: string[] = [billToSource.name || ''];
  const billAddr = (billToSource.address || '').trim();
  if (billAddr) billAddr.split(',').map((p) => p.trim()).filter(Boolean).forEach((p) => billToLines.push(p));
  if (billToSource.phone) billToLines.push(`PHONE: ${billToSource.phone}`);
  const billToContent = billToLines.join('\n');
  const tableWidth = pageWidth - margin * 2;
  const headCols: string[] = [];
  const bodyCols: string[] = [];
  if (template.showBillTo) {
    headCols.push('BILL TO');
    bodyCols.push(billToContent);
  }
  if (template.showShipTo) {
    headCols.push('SHIP TO');
    bodyCols.push(shipToContent);
  }
  const colCount = headCols.length;
  const colWidth = tableWidth / colCount;
  const columnStyles: Record<number, { cellWidth: number }> = {};
  for (let i = 0; i < colCount; i++) columnStyles[i] = { cellWidth: colWidth };
  const autoTableFn = jspdfAutoTable.default || jspdfAutoTable.autoTable || jspdfAutoTable;
  autoTableFn(doc, {
    startY,
    head: [headCols],
    body: [bodyCols],
    columnStyles,
    styles: { fontSize: 6, cellPadding: 2 },
    headStyles: {
      fillColor: BILL_SHIP_HEADER_COLOR,
      textColor: [255, 255, 255],
      fontStyle: 'normal',
      fontSize: 6,
    },
    margin: { left: leftX, right: margin },
    tableWidth,
  });
  return (doc as any).lastAutoTable.finalY;
}

function addInvoiceHeaderToPage(
  doc: jsPDF,
  orderData: InvoiceOrderData,
  template: InvoiceTemplateConfig,
  pageNum: number,
  totalPages: number,
  logoDataUrl: string | null
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 10;
  const contentWidth = pageWidth - margin * 2;
  const dist = orderData.distributor;
  const logoPosition = template.logoPosition;
  const showLogo = template.showLogo;
  const showDistributorDetails = template.showDistributorDetails;
  const showPageOf = template.showPageOf;
  const showHeaderMessage = template.showHeaderMessage;
  const headerMessageFirstPage = template.headerMessageFirstPage || '';

  // Layout: "left" = 20% logo | 35% distributor | 45% tables. "center" (beside distributor) = 35% distributor (left) | 20% logo | 45% tables.
  const logoColWidth = contentWidth * 0.2;
  const distColWidth = contentWidth * 0.35;
  // Logo width = 85% of the 20% logo column width
  const logoW = logoColWidth * 0.70;
  const logoH = 24; 

  let distStartX: number;
  let logoStartX: number;
  let rightStartX: number;
  let rightTableWidth: number;
  if (logoPosition === 'center') {
    // Beside distributor: first 35% distributor (left), then 20% logo, then 45% tables
    distStartX = margin;
    logoStartX = margin + distColWidth + 4;
    rightStartX = margin + distColWidth + logoColWidth + 8;
    rightTableWidth = pageWidth - margin - rightStartX;
  } else {
    // Left or right: 20% logo column | 35% distributor | 45% tables
    logoStartX = margin;
    distStartX = margin + logoColWidth + 4;
    rightStartX = margin + logoColWidth + distColWidth + 8;
    rightTableWidth = pageWidth - margin - rightStartX;
  }

  let headerStartY = 6;
  if (showPageOf) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, 6, {
      align: 'right',
    });
    headerStartY = 10;
  }

  let leftBottom = headerStartY;
  // Logo in left 20% only when position is 'left'
  if (showLogo && logoDataUrl && logoPosition === 'left') {
    try {
      doc.addImage(logoDataUrl, 'PNG', logoStartX, headerStartY, logoW, logoH);
      leftBottom = headerStartY + logoH + 2;
    } catch {
      leftBottom = headerStartY + 4;
    }
  }

  // Distributor block (35%): INVOICE title + distributor details at distStartX
  let centerY = headerStartY;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('INVOICE', distStartX, centerY);
  centerY += 6;
  if (showDistributorDetails) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(dist.name, distStartX, centerY);
    centerY += 5;
    doc.setFontSize(7);
    if (dist.address) {
      const addrLines = dist.address.split(', ');
      addrLines.forEach((line: string) => {
        doc.text(line.trim(), distStartX, centerY);
        centerY += 4;
      });
    }
    if (dist.orderLine) {
      doc.text(`Order Line: ${dist.orderLine}`, distStartX, centerY);
      centerY += 4;
    }
    if (dist.phoneFax) {
      doc.text(`Phone/Fax: ${dist.phoneFax}`, distStartX, centerY);
      centerY += 4;
    }
    if (dist.whatsapp) {
      doc.text(`Whatsapp #: ${dist.whatsapp}`, distStartX, centerY);
      centerY += 4;
    }
  }

  // When "beside distributor": logo in the 20% column to the right of distributor block
  if (logoPosition === 'center' && showLogo && logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, 'PNG', logoStartX, headerStartY, logoW, logoH);
      leftBottom = Math.max(leftBottom, headerStartY + logoH + 2);
    } catch {
      // ignore
    }
  }
  if (logoPosition === 'center') {
    leftBottom = Math.max(leftBottom, centerY);
  }

  // Right 45%: logo when position is 'right', then invoice info tables
  let tablesStartY = headerStartY;
  if (logoPosition === 'right' && showLogo && logoDataUrl) {
    try {
      const logoRightX = pageWidth - margin - logoW;
      doc.addImage(logoDataUrl, 'PNG', logoRightX, headerStartY, logoW, logoH);
      tablesStartY = headerStartY + logoH + 2;
    } catch {
      // ignore
    }
  }
  const tablesBottom = drawHeaderTables(doc, orderData, template, rightStartX, tablesStartY, rightTableWidth, pageWidth, margin);
  const headerBlockBottom = Math.max(leftBottom, centerY, tablesBottom) + 4;

  // Header message above Bill To / Ship To: 100% width, max 3 lines
  let billShipStartY = headerBlockBottom;
  if (showHeaderMessage && headerMessageFirstPage && pageNum === 1) {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    const plainHeaderMsg = stripHtmlAndTruncate(headerMessageFirstPage, 750);
    const headerMsgMaxWidth = contentWidth - 2;
    const headerMsgLines: string[] = [];
    plainHeaderMsg.split(/\n/).forEach((para) => {
      const wrapped = wrapFooterMessage(doc, para.trim(), headerMsgMaxWidth, 3 - headerMsgLines.length);
      wrapped.forEach((l) => {
        if (headerMsgLines.length < 3) headerMsgLines.push(l);
      });
    });
    headerMsgLines.slice(0, 3).forEach((line) => {
      doc.text(line, margin, billShipStartY);
      billShipStartY += 3.5;
    });
    billShipStartY += 2;
  }

  // BILL TO / SHIP TO (same customer)
  const billShipBottom = drawBillToShipTo(doc, orderData, template, billShipStartY, margin, pageWidth, margin);

  const headerBottom = billShipBottom + 4;
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.3);
  doc.line(margin, headerBottom + 2, pageWidth - margin, headerBottom + 2);
  return headerBottom + 6;
}

function addInvoiceSummaryHeaderToPage(
  doc: jsPDF,
  orderData: InvoiceOrderData,
  template: InvoiceTemplateConfig,
  pageNum: number,
  totalPages: number,
  logoDataUrl: string | null
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 10;
  const colWidth = (pageWidth - margin * 2) / 3;
  const leftX = margin;
  const midX = margin + colWidth;
  const rightX = margin + colWidth * 2;
  const smallLogoW = 12;
  const smallLogoH = 9;
  const summaryStartY = template.showPageOf ? 8 : 5;
  const cust = orderData.customer;
  const dist = orderData.distributor;
  const logoPosition = template.logoPosition;

  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  if (template.showPageOf) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, 5, {
      align: 'right',
    });
    doc.setFontSize(7);
    doc.setTextColor(0, 0, 0);
  }

  const drawSummaryLogo = (x: number) => {
    const logoX = logoPosition === 'left' && x === leftX ? x : x + (colWidth - smallLogoW) / 2;
    if (template.showLogo && logoDataUrl) {
      try {
        doc.addImage(logoDataUrl, 'PNG', logoX, summaryStartY - 1, smallLogoW, smallLogoH);
      } catch {
        // no logo render: do not show placeholder
      }
    }
  };
  const drawSummaryDistributor = (x: number) => {
    if (template.showDistributorDetails) {
      doc.text(dist.name, x, summaryStartY + 3, { align: 'left' });
    }
  };
  const drawSummaryCustomer = (x: number) => {
    const rightEdge = x + colWidth;
    let y = summaryStartY + 3;
    if (template.showCustomerDetails) {
      doc.text(`${cust.number}, ${cust.name}`, rightEdge, y, { align: 'right' });
      y += 5;
    }
    if (template.showDocNumber) {
      doc.text(`Invoice: ${orderData.invoiceNumber}`, rightEdge, y, { align: 'right' });
    }
  };

  // No right logo: treat 'right' as 'left'
  const summaryLogoPos = logoPosition === 'right' ? 'left' : logoPosition;
  if (summaryLogoPos === 'center') {
    drawSummaryDistributor(leftX);
    drawSummaryLogo(midX);
    drawSummaryCustomer(rightX);
  } else {
    drawSummaryLogo(leftX);
    drawSummaryDistributor(midX);
    drawSummaryCustomer(rightX);
  }

  const lineY = summaryStartY + smallLogoH + 4;
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.3);
  doc.line(margin, lineY, pageWidth - margin, lineY);
  return lineY + 6;
}

function stripHtml(html: string): string {
  if (typeof document === 'undefined') return html.replace(/<[^>]*>/g, '').trim();
  const div = document.createElement('div');
  div.innerHTML = html;
  return (div.textContent || div.innerText || '').trim();
}

/** Strip HTML and truncate to maxLen chars (header 750, footer 1000). */
function stripHtmlAndTruncate(text: string, maxLen: number): string {
  if (!text || typeof text !== 'string') return '';
  const stripped = stripHtml(text);
  return stripped.slice(0, maxLen).trim();
}

/** Wrap text into lines of max width (mm); preserves user newlines (line-by-line). Returns array of lines (~maxLines). Exported for preview. */
export function wrapFooterMessage(doc: jsPDF, text: string, maxWidthMm: number, maxLines = 7): string[] {
  const lines: string[] = [];
  doc.setFontSize(7);
  // Split by newlines first so footer message line-by-line input is preserved
  const paragraphs = text.split(/\r?\n/).map((p) => p.trim()).filter(Boolean);
  for (const para of paragraphs) {
    if (lines.length >= maxLines) break;
    const words = para.split(/\s+/).filter(Boolean);
    let current = '';
    for (const w of words) {
      const next = current ? `${current} ${w}` : w;
      if (doc.getTextWidth(next) <= maxWidthMm) {
        current = next;
      } else {
        if (current) {
          lines.push(current);
          if (lines.length >= maxLines) break;
        }
        current = w;
      }
    }
    if (current && lines.length < maxLines) lines.push(current);
  }
  return lines;
}

function addInvoiceFooterToPage(
  doc: jsPDF,
  orderData: InvoiceOrderData,
  template: InvoiceTemplateConfig,
  logoDataUrl: string | null,
  isLastPage: boolean,
  _categoryTableBottomY?: number
): void {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 10;
  const tot = orderData.totals;
  const subTotal = tot.subTotal ?? 0;
  const deliveryCharge = tot.deliveryCharge ?? 0;
  const deposit = tot.deposit ?? 0;
  const lastBalance = tot.lastBalance ?? 0;
  const houseCharge = tot.houseCharge ?? 0;
  const posCheck = tot.posCheck ?? 0;
  const posCash = tot.posCash ?? 0;
  const posCredit = tot.posCredit ?? 0;
  // Invoice total always includes houseCharge and posCheck/posCash/posCredit in the calculation,
  // even when showHouseCharge/showPosCheck etc. are false (those flags only control display of the line, not the total).
  const baseTotal = subTotal + deliveryCharge + deposit;
  const invoiceTotal = Number((baseTotal + houseCharge - posCheck - posCash - posCredit).toFixed(2));
  const totalAmountDue = Number((invoiceTotal - lastBalance).toFixed(2));

  // Footer at bottom: Woopsa line at page bottom; on last page, footer block sits just above it (no gap).
  const woopsaY = pageHeight - WOOPSA_LINE_BOTTOM_MM;
  const gapFooterToWoopsaMM = 1;
  const footerBlockMaxTop = woopsaY - gapFooterToWoopsaMM - LAST_PAGE_FOOTER_BLOCK_MM;
  const footerBlockTop = footerBlockMaxTop;

  // Divider above footer only on last page
  if (isLastPage) {
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.3);
    doc.line(margin, footerBlockTop - 2, pageWidth - margin, footerBlockTop - 2);
  }

  // Footer block (summary + message) only on last page
  if (isLastPage) {
    const contentWidth = pageWidth - margin * 2;
    const summaryWidth = contentWidth * 0.25;
    const messageWidth = contentWidth * 0.75;
    const messageLeft = template.footerLayout === 'messageLeft';
    // messageRight: summary left (25%) align left, message right (75%). messageLeft: message left (75%), summary right (25%) align right.
    const summaryX = messageLeft ? margin + messageWidth + 4 : margin + 2;
    const summaryAlign = messageLeft ? 'right' : 'left';
    const summaryTextX = messageLeft ? pageWidth - margin : summaryX;
    const messageX = messageLeft ? margin : margin + summaryWidth + 4;

    const footerBlockHeight = Math.min(LAST_PAGE_FOOTER_BLOCK_MM, Math.max(0, woopsaY - gapFooterToWoopsaMM - footerBlockTop));
    doc.setFillColor(255, 255, 255);
    doc.rect(margin, footerBlockTop, contentWidth, footerBlockHeight, 'F');

    // Subtotal = sum of extended totals (matches extended total column: with PPD or without PPD)
    const useWithoutPPD = template.extendedTotalBasedOn === 'withoutPPD';
    const subTotalForDisplay = (orderData.items || []).reduce((s, i) => {
      const qty = Number(i.shippedQty) || 0;
      const ext = useWithoutPPD
        ? (i.priceWithTaxWithoutPPD ?? (i.priceWithTax - (i.prepaidTaxAmount ?? 0))) * qty
        : (i.priceWithTaxWithPPD ?? i.priceWithTax) * qty;
      return s + ext;
    }, 0);

    let summaryY = footerBlockTop + 5;
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    const totalPrepaidTax = orderData.totals.totalPrepaidTax ?? 0;
    const lbl = (key: string, defaultText: string) =>
      (template.footerSummaryLabels?.[key]?.trim() || defaultText);
    // First line: Subtotal (with PPD) or Net invoice (without PPD). When with PPD, this is total price including prepaid tax.
    if (template.showSubTotal) {
      const subtotalLabel = lbl('netInvoice', useWithoutPPD ? 'Net invoice' : 'Subtotal');
      doc.text(`${subtotalLabel}: ${formatCurrency(subTotalForDisplay)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    // Show state Prepaid Sales Tax (e.g. "TN Prepaid Sales Tax") only when "EXT Price without PPD" is selected
    if (useWithoutPPD) {
      const stateLabel = lbl(
        'totalPPD',
        orderData.customer.state ? `${orderData.customer.state} Prepaid Sales Tax` : 'Prepaid Sales Tax'
      );
      doc.text(`${stateLabel}: ${formatCurrency(totalPrepaidTax)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    if (template.showDeliveryCharge) {
      doc.text(`${lbl('deliveryCharge', 'Delivery Charge')}: ${formatCurrency(deliveryCharge)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    if (template.showDeposit) {
      doc.text(`${lbl('deposit', 'Deposit')}: ${formatCurrency(deposit)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    if (template.showHouseCharge && houseCharge !== 0) {
      doc.text(`${lbl('houseCharge', 'House Charge')}: ${formatCurrency(houseCharge)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    if (template.showPosCheck && posCheck !== 0) {
      doc.text(`${lbl('posCheck', 'POS Check')}: ${formatCurrency(posCheck)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    if (template.showPosCash && posCash !== 0) {
      doc.text(`${lbl('posCash', 'POS Cash')}: ${formatCurrency(posCash)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    if (template.showPosCredit && posCredit !== 0) {
      doc.text(`${lbl('posCredit', 'POS Credit')}: ${formatCurrency(posCredit)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    doc.text(`${lbl('invoiceTotal', 'Invoice Total')}: ${formatCurrency(invoiceTotal)}`, summaryTextX, summaryY, { align: summaryAlign });
    summaryY += 4;
    if (template.showLastBalance) {
      doc.text(`${lbl('lastBalance', 'Last Balance')}: ${formatCurrency(lastBalance)}`, summaryTextX, summaryY, { align: summaryAlign });
      summaryY += 4;
    }
    if (template.showTotalAmountDue) {
      doc.text(`${lbl('totalDue', 'Total Due')}: ${formatCurrency(totalAmountDue)}`, summaryTextX, summaryY, { align: summaryAlign });
    }

    if (template.showFooterMessage && template.footerMessageLastPage) {
      const plainMsg = stripHtmlAndTruncate(template.footerMessageLastPage, 1000);
      const msgLines = wrapFooterMessage(doc, plainMsg, messageWidth - 2, 7);
      const messageAlign = messageLeft ? 'left' : 'right';
      const messageTextX = messageLeft ? messageX : pageWidth - margin;
      let msgY = footerBlockTop + 4;
      msgLines.forEach((line) => {
        doc.text(line, messageTextX, msgY, { align: messageAlign });
        msgY += 3.5;
      });
    }
  }

  // Bottom line: left = hardcoded message, right = "Report generated by Woopsa" + logo
  const reportY = pageHeight - WOOPSA_LINE_BOTTOM_MM;
  doc.setFontSize(7);
  doc.setTextColor(0, 0, 0);
  const leftMsg = 'This is a computer-generated invoice.';
  doc.text(leftMsg, margin, reportY);
  if (template.showReportGeneratedByWoopsa) {
    doc.setTextColor(120, 120, 120);
    const reportText = 'Report generated by Woopsa';
    const logoW = 4;
    const logoH = 3.5;
    const rightX = pageWidth - margin;
    const textEndX = rightX - logoW - 2; // text ends 2mm left of logo
    doc.text(reportText, textEndX, reportY, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    if (logoDataUrl) {
      try {
        doc.addImage(logoDataUrl, 'PNG', rightX - logoW, reportY - logoH, logoW, logoH);
      } catch {
        // ignore
      }
    }
  }
}

/** Map API invoice template to InvoiceTemplateConfig (subset used by PDF). */
export function apiTemplateToInvoiceConfig(api: {
  groupBy?: string;
  showGroupHeader?: boolean;
  selectedColumns?: Record<string, boolean>;
  columnPlacement?: string;
  columnOrder?: Record<string, number>;
  extendedTotalBasedOn?: string;
  upcOption?: string;
  showDistributorDetails?: boolean;
  showCustomerDetails?: boolean;
  showBillTo?: boolean;
  showShipTo?: boolean;
  showDocNumber?: boolean;
  showPageOf?: boolean;
  showInvoiceDate?: boolean;
  showInvoiceDateWithTime?: boolean;
  showRoute?: boolean;
  showStop?: boolean;
  showLogo?: boolean;
  logoPosition?: string;
  showTerms?: boolean;
  headerOnPages?: string;
  showHeaderMessage?: boolean;
  headerMessageFirstPage?: string;
  footerLayout?: string;
  showFooterMessage?: boolean;
  footerMessageLastPage?: string;
  showSubTotal?: boolean;
  showDeliveryCharge?: boolean;
  showDeposit?: boolean;
  showHouseCharge?: boolean;
  showPosCheck?: boolean;
  showPosCash?: boolean;
  showPosCredit?: boolean;
  showLastBalance?: boolean;
  showTotalAmountDue?: boolean;
  showReportGeneratedByWoopsa?: boolean;
  footerSummaryLabels?: Record<string, string>;
  columnHeaderNames?: Record<string, string>;
}): InvoiceTemplateConfig {
  const defaultCols: Record<string, boolean> = {
    orderQty: true, shippedQty: true, itemNumber: true, description: true, pack: false, size: false, upc: true,
    sortNumber: false, ebt: false, retail1: false, deposit: false,
    price: true, unitPrice: false, tax: false, prepaidTaxAmount: false, totalPPD: false, priceWithTaxWithPPD: true, priceWithTaxWithoutPPD: false,
    extendedTotal: true,
  };
  // Merge so API selectedColumns override defaults but every column key exists (avoids missing fields)
  const selectedColumns = { ...defaultCols, ...(api?.selectedColumns ?? {}) };
  return {
    groupBy: normalizeGroupBy(api?.groupBy),
    showGroupHeader: api?.showGroupHeader ?? true,
    selectedColumns,
    columnPlacement: api?.columnPlacement === 'custom' ? 'custom' : 'default',
    columnOrder: api?.columnOrder && typeof api.columnOrder === 'object' ? { ...api.columnOrder } : undefined,
    extendedTotalBasedOn: selectedColumns.priceWithTaxWithoutPPD === true ? 'withoutPPD' : 'withPPD',
    upcOption: api?.upcOption || 'barcode_primary',
    showDistributorDetails: api?.showDistributorDetails ?? true,
    showCustomerDetails: api?.showCustomerDetails ?? true,
    showBillTo: api?.showBillTo ?? true,
    showShipTo: api?.showShipTo ?? true,
    showDocNumber: api?.showDocNumber ?? true,
    showPageOf: api?.showPageOf ?? true,
    showInvoiceDate: api?.showInvoiceDate ?? true,
    showInvoiceDateWithTime: api?.showInvoiceDateWithTime ?? false,
    showRoute: api?.showRoute ?? true,
    showStop: api?.showStop ?? true,
    showLogo: api?.showLogo ?? true,
    logoPosition: normalizeLogoPosition(api?.logoPosition),
    showTerms: api?.showTerms ?? true,
    headerOnPages: normalizeHeaderOnPages(api?.headerOnPages),
    showHeaderMessage: api?.showHeaderMessage ?? false,
    headerMessageFirstPage: api?.headerMessageFirstPage || '',
    footerLayout: normalizeFooterLayout(api?.footerLayout),
    showFooterMessage: api?.showFooterMessage ?? true,
    footerMessageLastPage: api?.footerMessageLastPage || '',
    showSubTotal: api?.showSubTotal ?? true,
    showDeliveryCharge: api?.showDeliveryCharge ?? true,
    showDeposit: api?.showDeposit ?? true,
    showHouseCharge: api?.showHouseCharge ?? false,
    showPosCheck: api?.showPosCheck ?? false,
    showPosCash: api?.showPosCash ?? false,
    showPosCredit: api?.showPosCredit ?? false,
    showLastBalance: api?.showLastBalance ?? true,
    showTotalAmountDue: api?.showTotalAmountDue ?? true,
    showReportGeneratedByWoopsa: api?.showReportGeneratedByWoopsa ?? true,
    footerSummaryLabels: api?.footerSummaryLabels && typeof api.footerSummaryLabels === 'object' ? { ...api.footerSummaryLabels } : undefined,
    columnHeaderNames: api?.columnHeaderNames && typeof api.columnHeaderNames === 'object' ? { ...api.columnHeaderNames } : undefined,
  };
}

/** Options for generateInvoicePDF: print opens print dialog instead of downloading. */
export interface GenerateInvoicePDFOptions {
  /** If true, open print dialog instead of downloading the PDF. */
  print?: boolean;
  /** Optional warehouse/distributor logo URL (e.g. from auth.wareHouseDetail[0].D_Logo). Used for header and "Report generated by Woopsa" footer when Contact Us has no logo. */
  warehouseLogoUrl?: string;
}

/** Contact Us API shape (distributor details + logo). */
interface ContactUsData {
  D_Name?: string;
  D_Addr1?: string;
  D_City?: string;
  D_State?: string;
  D_Zip?: string;
  D_OrderLine?: string;
  D_Phone?: string;
  D_Whatsapp?: string;
  D_Logo?: string;
  logo?: string;
}

/** Format numeric cell for display: use data when present, otherwise 0.00 for price-like fields. */
function formatInvoiceCellValue(key: string, v: unknown): string {
  const num = v !== null && v !== undefined ? Number(v) : NaN;
  if (key === 'orderQty' || key === 'shippedQty') {
    return Number.isNaN(num) ? '0' : String(Math.round(num));
  }
  if (['price', 'unitPrice', 'tax', 'prepaidTaxAmount', 'totalPPD', 'priceWithTaxWithPPD', 'priceWithTaxWithoutPPD', 'extendedTotal', 'totalPrice', 'retail1', 'deposit'].includes(key)) {
    return Number.isNaN(num) ? '0.00' : Number(num).toFixed(2);
  }
  if (v === null || v === undefined) return '';
  return String(v);
}

/** Build one group-subtotal row: Price, EXT Price with/without PPD, extended total, totalPPD sums; per-unit columns blank. */
function buildGroupSubtotalRow(
  selectedKeys: string[],
  groupLabel: string,
  items: InvoiceLineItem[],
  template: InvoiceTemplateConfig
): string[] {
  const orderQtySum = items.reduce((s, i) => s + (Number(i.orderQty) || 0), 0);
  const shippedQtySum = items.reduce((s, i) => s + (Number(i.shippedQty) || 0), 0);
  const useWithoutPPD = template.extendedTotalBasedOn === 'withoutPPD';
  const extendedTotalSum = items.reduce((s, i) => {
    const qty = Number(i.shippedQty) || 0;
    const ext = useWithoutPPD
      ? (i.priceWithTaxWithoutPPD ?? (i.priceWithTax - (i.prepaidTaxAmount ?? 0))) * qty
      : (Number(i.totalPrice) || 0);
    return s + ext;
  }, 0);
  const totalPPDSum = items.reduce((s, i) => s + (Number(i.prepaidTaxAmount ?? 0) * (Number(i.shippedQty) || 0)), 0);
  const priceSum = items.reduce((s, i) => s + (Number(i.price) || 0) * (Number(i.shippedQty) || 0), 0);
  const priceWithPPDSum = items.reduce((s, i) => {
    const qty = Number(i.shippedQty) || 0;
    return s + (i.priceWithTaxWithPPD ?? i.priceWithTax ?? 0) * qty;
  }, 0);
  const priceWithoutPPDSum = items.reduce((s, i) => {
    const qty = Number(i.shippedQty) || 0;
    return s + (i.priceWithTaxWithoutPPD ?? (i.priceWithTax - (i.prepaidTaxAmount ?? 0))) * qty;
  }, 0);
  return selectedKeys.map((key) => {
    if (key === 'description') return groupLabel;
    if (key === 'orderQty') return String(Math.round(orderQtySum));
    if (key === 'shippedQty') return String(Math.round(shippedQtySum));
    if (key === 'price') return priceSum.toFixed(2);
    if (key === 'priceWithTaxWithPPD') return priceWithPPDSum.toFixed(2);
    if (key === 'priceWithTaxWithoutPPD') return priceWithoutPPDSum.toFixed(2);
    if (key === 'extendedTotal') return extendedTotalSum.toFixed(2);
    if (key === 'totalPPD') return totalPPDSum.toFixed(2);
    if (key === 'prepaidTaxAmount' || key === 'unitPrice') return '';
    if (key === 'pack' || key === 'size' || key === 'deposit' || key === 'ebt') return '';
    return '';
  });
}

/** Compute sales category summary: category -> { qty, extended }. EXTEN uses same basis as extended total (EXT Price with PPD or without PPD). */
function getCategorySummary(
  items: InvoiceLineItem[],
  extendedTotalBasedOn?: string
): Array<{ category: string; qty: number; extended: number }> {
  const useWithoutPPD = extendedTotalBasedOn === 'withoutPPD';
  const map: Record<string, { qty: number; extended: number }> = {};
  items.forEach((item) => {
    const cat = item.salesCategory || 'Other';
    if (!map[cat]) map[cat] = { qty: 0, extended: 0 };
    const qty = Number(item.shippedQty) || Number(item.orderQty) || 0;
    map[cat].qty += qty;
    const ext = useWithoutPPD
      ? (item.priceWithTaxWithoutPPD ?? (item.priceWithTax - (item.prepaidTaxAmount ?? 0))) * qty
      : Number(item.totalPrice) || 0;
    map[cat].extended += ext;
  });
  return Object.keys(map)
    .sort()
    .map((category) => ({ category, qty: map[category].qty, extended: map[category].extended }));
}

/**
 * Generate invoice PDF using order data and template config (same layout/conditions as InvoiceTemplateTab preview).
 * Distributor details and logo are loaded from Contact Us when available.
 * When options.print is true, opens print dialog instead of downloading.
 */
export async function generateInvoicePDF(
  orderData: InvoiceOrderData,
  template: InvoiceTemplateConfig,
  options?: GenerateInvoicePDFOptions
): Promise<void> {
  let contactData: ContactUsData | null = null;
  try {
    const data = await getContactUsData();
    contactData = Array.isArray(data) ? (data[0] as ContactUsData) ?? null : (data as ContactUsData) ?? null;
  } catch {
    // use orderData.distributor and default logo
  }
  const distributorFromContact =
    contactData &&
    (contactData.D_Name || contactData.D_Addr1 || contactData.D_City || contactData.D_State || contactData.D_Zip)
      ? {
          name: contactData.D_Name ?? orderData.distributor.name,
          address:
            [contactData.D_Addr1, contactData.D_City, contactData.D_State, contactData.D_Zip]
              .filter(Boolean)
              .join(', ') || (orderData.distributor.address ?? ''),
          orderLine: contactData.D_OrderLine ?? orderData.distributor.orderLine,
          phoneFax: contactData.D_Phone ?? orderData.distributor.phoneFax,
          whatsapp: contactData.D_Whatsapp ?? orderData.distributor.whatsapp,
        }
      : null;
  const pdfOrderData: InvoiceOrderData = distributorFromContact
    ? { ...orderData, distributor: distributorFromContact }
    : orderData;
  // Warehouse logo for header: optional explicit URL first, then Contact Us (logo or D_Logo).
  const warehouseLogoUrl = options?.warehouseLogoUrl || contactData?.logo || contactData?.D_Logo;
  const logoFromContact = warehouseLogoUrl ? await loadLogoFromUrl(warehouseLogoUrl) : null;
  // "Report generated by Woopsa" footer always uses Rabbit logo only (not warehouse logo).
  const footerLogo = await loadRabbitLogoAsDataUrl();
  let selectedKeys = getOrderedSelectedKeys(template);
  // PDF only: show EBT column only if at least one item has ebt true; when shown, header is empty (no "EBT" label)
  if (selectedKeys.includes('ebt')) {
    const hasAnyEbt = pdfOrderData.items.some((item) => item.ebt === true);
    if (!hasAnyEbt) selectedKeys = selectedKeys.filter((k) => k !== 'ebt');
  }
  const upcColIndex = selectedKeys.indexOf('upc');
  const descriptionColIndex = selectedKeys.indexOf('description');
  const showUpcAsBarcode = template.upcOption.startsWith('barcode');
  const columnStyles: Record<number, { cellWidth: number }> = {};
  if (descriptionColIndex >= 0) {
    columnStyles[descriptionColIndex] = { cellWidth: DESCRIPTION_COLUMN_WIDTH_MM };
  }
  const doc = new jsPDF('landscape', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  const headerHeight = addInvoiceHeaderToPage(doc, pdfOrderData, template, 1, 1, logoFromContact);
  const tableMarginTopNewPages =
    template.headerOnPages === 'all'
      ? headerHeight
      : template.headerOnPages === 'firstPlusSummary'
        ? SUMMARY_HEADER_HEIGHT_MM
        : margin;
  let yPos = headerHeight + 2;
  const grouped = groupInvoiceItems(template, pdfOrderData.items);
  // EBT column: no table header (empty label) when shown. Use columnHeaderNames from template when set.
  const headerLabels = selectedKeys.map((k) => {
    const custom = template.columnHeaderNames?.[k]?.trim();
    if (custom) return custom;
    return k === 'ebt' ? '' : (INVOICE_COLUMN_FIELDS.find((f) => f.key === k)?.label || k);
  });
  const autoTableFn = jspdfAutoTable.default || jspdfAutoTable.autoTable || jspdfAutoTable;
  const tableBottomMarginMM = getTableBottomMarginMM(template);
  const totalPagesEstimate = estimateTotalPages(
    grouped,
    template,
    headerHeight,
    tableMarginTopNewPages,
    pageHeight,
    tableBottomMarginMM
  );

  const itemsTableWidth = pageWidth - margin * 2;
  const showGroupSubtotal =
    template.groupBy === 'alphabetSalesCategory' || template.groupBy === 'sequence';

  const getMinYBeforeFooter = (): number => {
    const currentPage = doc.getNumberOfPages();
    const marginBottom = currentPage === totalPagesEstimate ? tableBottomMarginMM : NON_LAST_PAGE_BOTTOM_MM;
    return pageHeight - marginBottom;
  };

  grouped.forEach((group, groupIdx) => {
    if (groupIdx > 0) yPos += 4;
    let minYBeforeFooter = getMinYBeforeFooter();
    if (template.groupBy === 'alphabetSalesCategory' && template.showGroupHeader && group.label != null) {
      if (yPos > minYBeforeFooter) {
        doc.addPage('a4', 'landscape');
        const currentP = doc.getNumberOfPages();
        if (template.headerOnPages === 'all') {
          yPos = addInvoiceHeaderToPage(doc, pdfOrderData, template, currentP, totalPagesEstimate, logoFromContact) + 2;
        } else if (template.headerOnPages === 'firstPlusSummary') {
          yPos = addInvoiceSummaryHeaderToPage(doc, pdfOrderData, template, currentP, totalPagesEstimate, logoFromContact) + 2;
        } else {
          yPos = tableMarginTopNewPages + 2;
        }
        minYBeforeFooter = getMinYBeforeFooter();
      }
      doc.setFillColor(240, 245, 250);
      doc.roundedRect(margin, yPos - 3, pageWidth - margin * 2, 6, 1, 1, 'FD');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`Sales Category: ${group.label}`, margin + 3, yPos + 1);
      yPos += 8;
    }
    if (template.groupBy === 'sequence' && template.showGroupHeader && group.key) {
      minYBeforeFooter = getMinYBeforeFooter();
      if (yPos > minYBeforeFooter) {
        doc.addPage('a4', 'landscape');
        const currentP = doc.getNumberOfPages();
        if (template.headerOnPages === 'all') {
          yPos = addInvoiceHeaderToPage(doc, pdfOrderData, template, currentP, totalPagesEstimate, logoFromContact) + 2;
        } else if (template.headerOnPages === 'firstPlusSummary') {
          yPos = addInvoiceSummaryHeaderToPage(doc, pdfOrderData, template, currentP, totalPagesEstimate, logoFromContact) + 2;
        } else {
          yPos = tableMarginTopNewPages + 2;
        }
        minYBeforeFooter = getMinYBeforeFooter();
      }
      doc.setFillColor(240, 245, 250);
      doc.roundedRect(margin, yPos - 3, pageWidth - margin * 2, 6, 1, 1, 'FD');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`Sequence: ${group.key}`, margin + 3, yPos + 1);
      yPos += 8;
    }
    minYBeforeFooter = getMinYBeforeFooter();
    if (yPos > minYBeforeFooter) {
      doc.addPage('a4', 'landscape');
      const currentP = doc.getNumberOfPages();
      if (template.headerOnPages === 'all') {
        yPos = addInvoiceHeaderToPage(doc, pdfOrderData, template, currentP, totalPagesEstimate, logoFromContact) + 2;
      } else if (template.headerOnPages === 'firstPlusSummary') {
        yPos = addInvoiceSummaryHeaderToPage(doc, pdfOrderData, template, currentP, totalPagesEstimate, logoFromContact) + 2;
      } else {
        yPos = tableMarginTopNewPages + 2;
      }
      minYBeforeFooter = getMinYBeforeFooter();
    }
    const currentPageForMargin = doc.getNumberOfPages();
    const marginBottomThisPage =
      currentPageForMargin === totalPagesEstimate ? tableBottomMarginMM : NON_LAST_PAGE_BOTTOM_MM;
    doc.setFontSize(7);
    const descColWidthMm = DESCRIPTION_COLUMN_WIDTH_MM - 3;
    const itemRows = group.items.map((item) =>
      selectedKeys.map((key) => {
        if (key === 'ebt') return item.ebt ? 'E' : '';
        if (key === 'upc' && showUpcAsBarcode) return '';
        if (key === 'description') {
          const descLines = wrapFooterMessage(doc, item.description || '', descColWidthMm, 15);
          return descLines.join('\n') + (item.outOfStockNote ? '\n*This item was out of stock' : '');
        }
        let v: unknown = (item as unknown as Record<string, unknown>)[key];
        if (v === undefined || v === null) {
          if (key === 'priceWithTaxWithPPD') v = item.priceWithTax;
          else if (key === 'priceWithTaxWithoutPPD') v = item.priceWithTaxWithoutPPD ?? (item.priceWithTax - (item.prepaidTaxAmount ?? 0));
          else if (key === 'unitPrice') v = item.unitPrice ?? item.price;
          else if (key === 'prepaidTaxAmount') v = item.prepaidTaxAmount;
          else if (key === 'totalPPD') v = (item.prepaidTaxAmount ?? 0) * (item.shippedQty || 0);
          else if (key === 'extendedTotal') {
            const useWithoutPPD = template.extendedTotalBasedOn === 'withoutPPD';
            const qty = item.shippedQty || 0;
            v = useWithoutPPD
              ? (item.priceWithTaxWithoutPPD ?? (item.priceWithTax - (item.prepaidTaxAmount ?? 0))) * qty
              : (item.totalPrice ?? 0);
          }
        }
        return formatInvoiceCellValue(key, v);
      })
    );
    const body: string[][] = [...itemRows];
    if (showGroupSubtotal && (template.groupBy === 'alphabetSalesCategory' || template.groupBy === 'sequence')) {
      const groupLabel =
        template.groupBy === 'alphabetSalesCategory' ? (group.label ?? group.key) : `Sequence: ${group.key}`;
      body.push(buildGroupSubtotalRow(selectedKeys, groupLabel, group.items, template));
    }
    const currentGroupItems = group.items;
    const subtotalRowIndex = body.length - 1;
    const hasSubtotalRow = showGroupSubtotal && (template.groupBy === 'alphabetSalesCategory' || template.groupBy === 'sequence') && body.length > group.items.length;
    const rowStyles: Record<number, { fillColor: number[] }> = {};
    body.forEach((_, i) => {
      rowStyles[i] = i === subtotalRowIndex && hasSubtotalRow
        ? { fillColor: [220, 220, 220] }
        : { fillColor: i % 2 === 0 ? [248, 248, 248] : [255, 255, 255] };
    });
    autoTableFn(doc, {
      head: [headerLabels],
      body,
      startY: yPos,
      tableWidth: itemsTableWidth,
      styles: { fontSize: 7, cellPadding: 1.5 },
      headStyles: { fillColor: [240, 240, 240], fontSize: 7, textColor: [0, 0, 0], fontStyle: 'normal' },
      columnStyles: Object.keys(columnStyles).length > 0 ? columnStyles : undefined,
      rowStyles: Object.keys(rowStyles).length > 0 ? rowStyles : undefined,
      margin: {
        left: margin,
        right: margin,
        top: tableMarginTopNewPages,
        bottom: marginBottomThisPage,
      },
      didDrawCell: (data: { section: string; row: { index: number }; column: { index: number }; cell: { x: number; y: number; width: number; height: number } }) => {
        if (data.section !== 'body' || data.row.index >= currentGroupItems.length) return;
        const item = currentGroupItems[data.row.index];
        if (upcColIndex >= 0 && data.column.index === upcColIndex && showUpcAsBarcode) {
          const upc = item?.upc;
          if (upc) {
            const barcodeDataUrl = generateBarcodeDataUrl(upc);
            if (barcodeDataUrl) {
              try {
                const w = Math.min(data.cell.width - 1, 38);
                const h = Math.min(data.cell.height - 1, 18);
                doc.addImage(barcodeDataUrl, 'PNG', data.cell.x + 0.5, data.cell.y + 0.5, w, h);
              } catch {
                doc.setFontSize(6);
                doc.text(upc, data.cell.x + 1, data.cell.y + data.cell.height / 2 + 1);
              }
            }
          }
          return;
        }
        if (descriptionColIndex >= 0 && data.column.index === descriptionColIndex && item?.outOfStockNote) {
          const rowFill = data.row.index % 2 === 0 ? [248, 248, 248] : [255, 255, 255];
          doc.setFillColor(rowFill[0], rowFill[1], rowFill[2]);
          doc.rect(data.cell.x, data.cell.y, data.cell.width, data.cell.height, 'F');
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(0, 0, 0);
          const cellPad = 1.5;
          const lineHeightMm = 3.5;
          doc.setFontSize(7);
          const descLines = wrapFooterMessage(doc, item.description || '', data.cell.width - cellPad * 2, 15);
          descLines.forEach((line, i) => {
            doc.setFontSize(7);
            doc.text(line, data.cell.x + cellPad, data.cell.y + 4 + i * lineHeightMm);
          });
          doc.setFontSize(5);
          doc.text('*This item was out of stock', data.cell.x + cellPad, data.cell.y + 4 + descLines.length * lineHeightMm);
        }
      },
    });
    yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 2;
  });

  let categoryTableBottomY: number | undefined;
  const pagesBeforeCategory = doc.getNumberOfPages();
  if (pagesBeforeCategory > 0) {
    doc.setPage(pagesBeforeCategory);
    const lastPageY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? yPos;
    const categorySummary = getCategorySummary(pdfOrderData.items, template.extendedTotalBasedOn);
    const totalQty = categorySummary.reduce((s, c) => s + c.qty, 0);
    const totalExtended = categorySummary.reduce((s, c) => s + c.extended, 0);
    if (categorySummary.length > 0) {
      // Reserve space above footer: content must end above this Y to avoid overlap with footer
      const footerZoneTopY = pageHeight - WOOPSA_LINE_BOTTOM_MM - 1 - LAST_PAGE_FOOTER_BLOCK_MM - GAP_CATEGORY_TO_FOOTER_MM;
      const categoryRows = categorySummary.length + 1; // +1 for TOTAL row
      const estimatedCategoryTableHeight = 6 + categoryRows * CATEGORY_TABLE_ROW_HEIGHT_MM; // header + rows
      const categoryStartY = lastPageY + 6;
      const wouldOverlapFooter = categoryStartY + estimatedCategoryTableHeight > footerZoneTopY;

      let startY: number;
      if (wouldOverlapFooter) {
        doc.addPage('a4', 'landscape');
        const newPageNum = doc.getNumberOfPages();
        if (template.headerOnPages === 'all') {
          startY = addInvoiceHeaderToPage(doc, pdfOrderData, template, newPageNum, newPageNum, logoFromContact) + 2;
        } else if (template.headerOnPages === 'firstPlusSummary') {
          startY = addInvoiceSummaryHeaderToPage(doc, pdfOrderData, template, newPageNum, newPageNum, logoFromContact) + 2;
        } else {
          startY = tableMarginTopNewPages + 2;
        }
      } else {
        startY = categoryStartY;
      }

      const categoryTableWidth = Math.min(itemsTableWidth, 120);
      const catCol1 = categoryTableWidth * 0.6;
      const catCol2 = categoryTableWidth * 0.2;
      const catCol3 = categoryTableWidth * 0.2;
      const categoryHead = [['QTY CATEGORY', 'QTY', 'EXTEN']];
      const categoryBody = categorySummary.map(({ category, qty, extended }) => [
        category,
        qty.toFixed(2),
        formatCurrency(extended),
      ]);
      categoryBody.push(['TOTAL', totalQty.toFixed(2), formatCurrency(totalExtended)]);
      autoTableFn(doc, {
        startY,
        head: categoryHead,
        body: categoryBody,
        columnStyles: { 0: { cellWidth: catCol1 }, 1: { cellWidth: catCol2 }, 2: { cellWidth: catCol3 } },
        styles: { fontSize: 7, cellPadding: 2 },
        headStyles: { fillColor: [220, 220, 220], fontSize: 7, textColor: [0, 0, 0], fontStyle: 'normal' },
        margin: { left: margin, right: margin },
        tableWidth: categoryTableWidth,
      });
      categoryTableBottomY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
    }
  }
  // Use page count after category table (it may have added a page if table didn't fit)
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addInvoiceFooterToPage(
      doc,
      pdfOrderData,
      template,
      footerLogo,
      i === totalPages,
      i === totalPages ? categoryTableBottomY : undefined
    );
    if (template.headerOnPages === 'first' && i > 1) {
      // no header on 2nd+ pages (same as InvoiceTemplateTab)
    } else if (template.headerOnPages === 'firstPlusSummary' && i > 1) {
      addInvoiceSummaryHeaderToPage(doc, pdfOrderData, template, i, totalPages, logoFromContact);
    } else {
      addInvoiceHeaderToPage(doc, pdfOrderData, template, i, totalPages, logoFromContact);
    }
  }

  if (options?.print) {
    try {
      doc.autoPrint();
      const blob = doc.output('blob');
      const url = URL.createObjectURL(blob);
      const printWindow = window.open(url, '_blank');
      if (printWindow) {
        printWindow.onload = () => printWindow.print();
        setTimeout(() => {
          try {
            printWindow.print();
          } catch {
            // ignore
          }
          URL.revokeObjectURL(url);
        }, 800);
      } else {
        URL.revokeObjectURL(url);
        const timestamp = new Date().toISOString().split('T')[0];
        doc.save(`invoice-${orderData.orderNumber}-${timestamp}.pdf`);
      }
    } catch {
      const timestamp = new Date().toISOString().split('T')[0];
      doc.save(`invoice-${orderData.orderNumber}-${timestamp}.pdf`);
    }
  } else {
    const timestamp = new Date().toISOString().split('T')[0];
    doc.save(`invoice-${orderData.orderNumber}-${timestamp}.pdf`);
  }
}
