import jsPDF from 'jspdf';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const jspdfAutoTable = require('jspdf-autotable');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const JsBarcode = require('jsbarcode');
// eslint-disable-next-line @typescript-eslint/no-require-imports
import rabbitLogo from '../assets/Rabbit.svg';
import { getPicklistTemplate } from '../redux/apis/distrubutor/settingApis';

// Template interface (same as in PicklistTemplateTab)
interface PicklistTemplate {
  id: string;
  name: string;
  selectedFields: { [key: string]: boolean };
  groupBy: 'salesCategory' | 'priceClass' | 'section' | 'location' | 'sectionSalesCategory' | 'locationSalesCategory' | 'sequence' | 'sequenceSalesCategory' | '';
  newCategoryOnNewPage: boolean;
  showSubHeader?: boolean;
  headerPosition: 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight';
  footerPosition: 'left' | 'right';
  pickedByPosition: 'top' | 'bottom';
  checkedByPosition: 'top' | 'bottom';
  // Header options
  showBarcode?: boolean;
  // Footer options - all configurable
  showTotalCartons?: boolean;
  showTotalPieces?: boolean;
  showTotalLines?: boolean;
  showPickedBy?: boolean;
  showCheckedBy?: boolean;
  showBundles?: boolean;
  createdAt: string;
  updatedAt: string;
}

// Field labels mapping
const FIELD_LABELS: { [key: string]: string } = {
  lineNumber: 'Line #',
  orderedQty: 'Ord Qty',
  scannedQty: 'Qty',
  itemNumber: 'Item Number',
  description: 'Description',
  pack: 'Pack',
  size: 'Size',
  upc: 'UPC',
  // onhand: 'On Hand',
  salesCategory: 'Sales Category',
  priceClass: 'Price Class',
  section: 'Section',
  location: 'Location',
  vendorItem: 'Vendor Item',
  sequence: 'Sequence',
};

// Generate barcode as data URL
const generateBarcodeDataUrl = (text: string): string | null => {
  try {
    const canvas = document.createElement('canvas');
    JsBarcode(canvas, text, {
      format: 'CODE128',
      width: 1.5,
      height: 30,
      displayValue: true,
      fontSize: 10,
      margin: 2,
    });
    return canvas.toDataURL('image/png');
  } catch (error) {
    console.error('Error generating barcode:', error);
    return null;
  }
};

// Load logo as data URL
const loadLogoAsDataUrl = async (): Promise<string | null> => {
  try {
    return new Promise<string | null>((resolve) => {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      
      img.onload = () => {
        try {
          const canvas = document.createElement('canvas');
          const ctx = canvas.getContext('2d');
          if (ctx) {
            canvas.width = img.width || 40;
            canvas.height = img.height || 33;
            ctx.drawImage(img, 0, 0);
            const dataUrl = canvas.toDataURL('image/png');
            resolve(dataUrl);
          } else {
            resolve(null);
          }
        } catch (error) {
          console.error('Error converting logo to canvas:', error);
          resolve(null);
        }
      };
      
      img.onerror = async () => {
        try {
          const logoPath = rabbitLogo;
          if (typeof rabbitLogo === 'string' && !rabbitLogo.startsWith('data:') && !rabbitLogo.startsWith('http')) {
            const response = await fetch(logoPath);
            if (response.ok) {
              const blob = await response.blob();
              const reader = new FileReader();
              reader.onloadend = () => {
                if (typeof reader.result === 'string') {
                  resolve(reader.result);
                } else {
                  resolve(null);
                }
              };
              reader.onerror = () => resolve(null);
              reader.readAsDataURL(blob);
              return;
            }
          }
          
          const publicResponse = await fetch('/Rabbit.svg');
          if (publicResponse.ok) {
            const blob = await publicResponse.blob();
            const reader = new FileReader();
            reader.onloadend = () => {
              if (typeof reader.result === 'string') {
                resolve(reader.result);
              } else {
                resolve(null);
              }
            };
            reader.onerror = () => resolve(null);
            reader.readAsDataURL(blob);
          } else {
            resolve(null);
          }
        } catch (fetchError) {
          console.error('Error fetching logo:', fetchError);
          resolve(null);
        }
      };
      
      if (typeof rabbitLogo === 'string') {
        img.src = rabbitLogo;
      } else {
        img.src = rabbitLogo as string;
      }
    });
  } catch (error) {
    console.error('Error loading logo:', error);
    return null;
  }
};

// Add footer to PDF - "Generated by Woopsa" centered at very bottom with proper margin
const addFooterToPage = (doc: jsPDF, logoDataUrl: string | undefined, _footerPosition: 'left' | 'right') => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // "Generated by Woopsa" text - centered at very bottom with margin
  const generatedByY = pageHeight - 5; // Very close to bottom, but with margin
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  const text = 'Picklist Generated by Woopsa';
  const textWidth = doc.getTextWidth(text);
  const textX = (pageWidth - textWidth) / 2; // Center horizontally
  
  doc.text(text, textX, generatedByY);
  
  // Logo next to text
  if (logoDataUrl) {
    try {
      const logoWidth = 4;
      const logoHeight = 4;
      const logoSpacing = 1.5;
      const logoX = textX + textWidth + logoSpacing;
      const logoY = generatedByY - 3.5;
      
      try {
        doc.addImage(logoDataUrl, 'PNG', logoX, logoY, logoWidth, logoHeight);
      } catch {
        try {
          doc.addImage(logoDataUrl, 'SVG', logoX, logoY, logoWidth, logoHeight);
        } catch {
          doc.addImage(logoDataUrl, logoX, logoY, logoWidth, logoHeight);
        }
      }
    } catch (error) {
      console.error('Error adding logo to PDF:', error);
    }
  }
};

// Add full header information to each page
const addFullHeaderToPage = (
  doc: jsPDF, 
  pageNum: number, 
  totalPages: number,
  orderData: any,
  template: PicklistTemplate
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 10;
  const headerStartY = 8;
  const yPos = headerStartY + 4;
  
  // Page number at top right (above header box)
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const pageText = `Page ${pageNum} of ${totalPages}`;
  const textWidth = doc.getTextWidth(pageText);
  doc.text(pageText, pageWidth - margin - textWidth, 6);
  
  // Calculate column widths (3 columns: left, middle, right)
  const leftColumnWidth = (pageWidth - (margin * 2)) * 0.35; // 35% for customer info
  const middleColumnWidth = (pageWidth - (margin * 2)) * 0.30; // 30% for barcode
  const leftX = margin + 2;
  const middleX = margin + leftColumnWidth + 5;
  const rightX = pageWidth - margin - 2;
  
  // First, calculate the header height by simulating content positions
  // This is needed to draw the background box first
  let estimatedRightHeight = 4; // Date
  estimatedRightHeight += 3.8; // Doc
  estimatedRightHeight += 3.8; // Order
  estimatedRightHeight += 4.5; // Distributor
  if (orderData.isReprint) estimatedRightHeight += 5;
  if (template.pickedByPosition === 'top' && template.showPickedBy !== false) estimatedRightHeight += 5;
  if (template.checkedByPosition === 'top' && template.showCheckedBy !== false) estimatedRightHeight += 5;
  
  let estimatedLeftHeight = 5; // Title spacing
  estimatedLeftHeight += 4.5; // Customer Information label
  estimatedLeftHeight += 3.5; // ID
  estimatedLeftHeight += 3.5; // Name
  estimatedLeftHeight += 3.5; // Address
  if (orderData.customer.phone) estimatedLeftHeight += 3.5; // Phone
  estimatedLeftHeight += 3.5; // Route/Stop
  
  const estimatedBarcodeHeight = 15; // Barcode height
  const estimatedMaxHeight = Math.max(estimatedLeftHeight, estimatedRightHeight, estimatedBarcodeHeight);
  const estimatedHeaderBoxHeight = estimatedMaxHeight + 8; // Add padding
  
  // Draw header background box FIRST (before content)
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, headerStartY, pageWidth - (margin * 2), estimatedHeaderBoxHeight, 1, 1, 'F');
  
  // Track actual Y positions as we render content
  let leftYPos = yPos;
  let rightYPos = yPos;
  let maxYPos = yPos;
  
  // Main title - PICKLIST (bold, larger) - Left column
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('PICKLIST', leftX, leftYPos);
  maxYPos = Math.max(maxYPos, leftYPos);
  
  // Middle column: Barcode of order number (doc number)
  const orderNumber = String(orderData.orderNumber || orderData.invoiceNumber || '');
  let barcodeBottomY = yPos;
  if (template.showBarcode !== false && orderNumber) {
    const barcodeDataUrl = generateBarcodeDataUrl(orderNumber);
    if (barcodeDataUrl) {
      try {
        const barcodeWidth = 25;
        const barcodeHeight = 15;
        const barcodeX = middleX + (middleColumnWidth - barcodeWidth) / 2;
        const barcodeY = yPos - 2;
        doc.addImage(barcodeDataUrl, 'PNG', barcodeX, barcodeY, barcodeWidth, barcodeHeight);
        barcodeBottomY = barcodeY + barcodeHeight;
        maxYPos = Math.max(maxYPos, barcodeBottomY);
      } catch (error) {
        console.error('Error adding barcode to PDF:', error);
      }
    }
  }
  
  // Right side: Document information section
  // Date
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Date:', rightX - 35, rightYPos, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.invoiceDate || orderData.orderDate || ''), rightX, rightYPos, { align: 'right' });
  rightYPos += 3.8;
  maxYPos = Math.max(maxYPos, rightYPos);
  
  // Doc Number
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  // doc.text('Doc:', rightX - 35, rightYPos, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.invoiceNumber || ''), rightX, rightYPos, { align: 'right' });
  rightYPos += 3.8;
  maxYPos = Math.max(maxYPos, rightYPos);
  
  // Order Number
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Order:', rightX - 35, rightYPos, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.orderNumber || ''), rightX, rightYPos, { align: 'right' });
  rightYPos += 3.8;
  maxYPos = Math.max(maxYPos, rightYPos);
  
  // Distributor
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Distributor:', rightX - 35, rightYPos, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(7);
  doc.text(orderData.distributor.name, rightX, rightYPos, { align: 'right' });
  rightYPos += 4.5;
  maxYPos = Math.max(maxYPos, rightYPos);
  
  // REPRINT badge
  if (orderData.isReprint) {
    doc.setFillColor(255, 240, 240);
    doc.setDrawColor(220, 0, 0);
    doc.setLineWidth(0.3);
    const reprintWidth = 20;
    const reprintX = rightX - reprintWidth;
    doc.roundedRect(reprintX, rightYPos - 3, reprintWidth, 4, 1, 1, 'FD');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(200, 0, 0);
    doc.text('REPRINT', rightX - reprintWidth / 2, rightYPos, { align: 'center' });
    rightYPos += 5;
    maxYPos = Math.max(maxYPos, rightYPos);
  }
  
  // Picked by and Checked by (right side, top position)
  if ((template.pickedByPosition === 'top' && template.showPickedBy !== false) || 
      (template.checkedByPosition === 'top' && template.showCheckedBy !== false)) {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    if (template.pickedByPosition === 'top' && template.showPickedBy !== false) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text('Picked by:', rightX - 35, rightYPos, { align: 'right' });
      doc.setDrawColor(180, 180, 180);
      doc.setLineWidth(0.2);
      doc.line(rightX - 30, rightYPos + 2, rightX, rightYPos + 2);
      rightYPos += 5;
      maxYPos = Math.max(maxYPos, rightYPos);
    }
    if (template.checkedByPosition === 'top' && template.showCheckedBy !== false) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text('Checked by:', rightX - 35, rightYPos, { align: 'right' });
      doc.setDrawColor(180, 180, 180);
      doc.setLineWidth(0.2);
      doc.line(rightX - 30, rightYPos + 2, rightX, rightYPos + 2);
      rightYPos += 5;
      maxYPos = Math.max(maxYPos, rightYPos);
    }
  }
  
  // Left side: Customer information section
  leftYPos += 5;
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Customer Information', leftX, leftYPos);
  leftYPos += 4.5;
  maxYPos = Math.max(maxYPos, leftYPos);
  
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  
  // Customer details with labels
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('ID:', leftX, leftYPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.customer.number), leftX + 8, leftYPos);
  leftYPos += 3.5;
  maxYPos = Math.max(maxYPos, leftYPos);
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Name:', leftX, leftYPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(orderData.customer.name, leftX + 12, leftYPos);
  leftYPos += 3.5;
  maxYPos = Math.max(maxYPos, leftYPos);
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Address:', leftX, leftYPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(orderData.customer.address, leftX + 15, leftYPos);
  leftYPos += 3.5;
  maxYPos = Math.max(maxYPos, leftYPos);
  
  if (orderData.customer.phone) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text('Phone:', leftX, leftYPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    doc.text(orderData.customer.phone, leftX + 12, leftYPos);
    leftYPos += 3.5;
    maxYPos = Math.max(maxYPos, leftYPos);
  }
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Route:', leftX, leftYPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.customer.route || ''), leftX + 12, leftYPos);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Stop:', leftX + 35, leftYPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.customer.stop), leftX + 42, leftYPos);
  maxYPos = Math.max(maxYPos, leftYPos);
  
  // Calculate actual header box height based on rendered content
  const actualContentHeight = maxYPos - headerStartY;
  const headerBoxHeight = Math.max(actualContentHeight + 8, estimatedHeaderBoxHeight); // Use actual or estimated, whichever is larger
  
  // Add divider below header (dark color like footer)
  const dividerY = headerStartY + headerBoxHeight + 2;
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(margin, dividerY, pageWidth - margin, dividerY);
  
  // Return the bottom position of header (divider + spacing) for table positioning
  return dividerY + 4; // Divider + spacing
};

// Natural/alphanumeric sort function for mixed alphanumeric strings (e.g., D, D01, DD2, DE1)
const naturalSort = (a: string, b: string): number => {
  // If both are numeric, sort numerically
  const aNum = parseFloat(a);
  const bNum = parseFloat(b);
  if (!isNaN(aNum) && !isNaN(bNum)) {
    return aNum - bNum;
  }
  
  // Natural sort for alphanumeric strings
  const aParts = a.match(/(\d+|\D+)/g) || [];
  const bParts = b.match(/(\d+|\D+)/g) || [];
  const maxLength = Math.max(aParts.length, bParts.length);
  
  for (let i = 0; i < maxLength; i++) {
    const aPart = aParts[i] || '';
    const bPart = bParts[i] || '';
    
    const aIsNum = !isNaN(parseFloat(aPart));
    const bIsNum = !isNaN(parseFloat(bPart));
    
    if (aIsNum && bIsNum) {
      const diff = parseFloat(aPart) - parseFloat(bPart);
      if (diff !== 0) return diff;
    } else if (aIsNum) {
      return -1; // Numbers come before non-numbers
    } else if (bIsNum) {
      return 1; // Numbers come before non-numbers
    } else {
      const diff = aPart.localeCompare(bPart);
      if (diff !== 0) return diff;
    }
  }
  
  return 0;
};

// Sort by description with priority: space, symbolic, numeric, alphabetic
const sortByDescription = (a: any, b: any): number => {
  const descA = String(a.description || '').trim();
  const descB = String(b.description || '').trim();
  
  // Get first character of each description
  const firstCharA = descA.charAt(0);
  const firstCharB = descB.charAt(0);
  
  // Get priority for first character: space (0), symbolic (1), numeric (2), alphabetic (3)
  const getPriority = (char: string): number => {
    if (char === ' ') return 0; // Space
    if (/[0-9]/.test(char)) return 2; // Numeric
    if (/[a-zA-Z]/.test(char)) return 3; // Alphabetic
    return 1; // Symbolic (everything else)
  };
  
  const priorityA = getPriority(firstCharA);
  const priorityB = getPriority(firstCharB);
  
  // Sort by priority first
  if (priorityA !== priorityB) {
    return priorityA - priorityB;
  }
  
  // If same priority, sort alphabetically
  return descA.localeCompare(descB);
};

// Helper function to safely get field value from item (handles both direct and nested inventory properties)
const getItemField = (item: any, field: string): any => {
  // Try direct property first (lowercase)
  if (item[field] !== undefined && item[field] !== null) {
    return item[field];
  }
  
  // For specific fields, handle nested objects in inventory
  if (field === 'salesCategory') {
    if (item.inventory?.SalesCategory?.Category_Desc) {
      return item.inventory.SalesCategory.Category_Desc;
    }
    // Fallback to direct property
    return item.salesCategory || null;
  }
  if (field === 'priceClass') {
    if (item.inventory?.PriceClass?.Class_Desc) {
      return item.inventory.PriceClass.Class_Desc;
    }
    // Fallback to direct property
    return item.priceClass || null;
  }
  if (field === 'section') {
    // Try inventory.Section (capital S) first, then fallback to direct property
    if (item.inventory?.Section !== undefined && item.inventory?.Section !== null) {
      return item.inventory.Section;
    }
    return item.section || null;
  }
  if (field === 'location') {
    // Try inventory.Location (capital L) first, then fallback to direct property
    if (item.inventory?.Location !== undefined && item.inventory?.Location !== null) {
      return item.inventory.Location;
    }
    return item.location || null;
  }
  if (field === 'sequence') {
    // Try inventory.Sequence first, then fallback to direct property
    if (item.inventory?.Sequence !== undefined && item.inventory?.Sequence !== null) {
      return item.inventory.Sequence;
    }
    return item.sequence || null;
  }
  if (field === 'vendorItem') {
    // Try inventory.Vendor_ItemNumberAlpha first, then fallback to direct property
    if (item.inventory?.Vendor_ItemNumberAlpha !== undefined && item.inventory?.Vendor_ItemNumberAlpha !== null) {
      return item.inventory.Vendor_ItemNumberAlpha;
    }
    return item.vendorItem || null;
  }
  
  // Fallback to inventory object if available (case-sensitive match)
  if (item.inventory && item.inventory[field] !== undefined && item.inventory[field] !== null) {
    return item.inventory[field];
  }
  
  return null;
};

// Group items based on selected grouping
const groupItems = (items: any[], groupBy: string) => {
  if (!groupBy) return [{ key: 'all', items: items.sort(sortByDescription) }];
  
  // Handle hierarchical grouping (Sales Category first, then Section/Location/Sequence)
  if (groupBy === 'sequenceSalesCategory') {
    // First group by Sales Category, then by Sequence within each category
    const primaryGrouped: { [key: string]: any[] } = {};
    
    items.forEach(item => {
      const salesCat = getItemField(item, 'salesCategory') || item.salesCategory || 'No Category';
      if (!primaryGrouped[salesCat]) {
        primaryGrouped[salesCat] = [];
      }
      primaryGrouped[salesCat].push(item);
    });
    
    // Sort primary groups alphabetically
    const sortedPrimaryKeys = Object.keys(primaryGrouped).sort();
    
    // Within each primary group, group by sequence and sort numerically
    const result: Array<{ salesCategory: string; subGroups: Array<{ key: string; items: any[] }> }> = [];
    sortedPrimaryKeys.forEach(primaryKey => {
      const secondaryGrouped: { [key: string]: any[] } = {};
      primaryGrouped[primaryKey].forEach(item => {
        const seqValue = getItemField(item, 'sequence') || item.sequence || 0;
        const seq = String(seqValue);
        if (!secondaryGrouped[seq]) {
          secondaryGrouped[seq] = [];
        }
        secondaryGrouped[seq].push(item);
      });
      
      // Sort sequences numerically
      const sortedSeqs = Object.keys(secondaryGrouped).sort((a, b) => parseInt(a) - parseInt(b));
      const subGroups = sortedSeqs.map(seq => ({
        key: seq,
        items: secondaryGrouped[seq].sort(sortByDescription)
      }));
      
      result.push({
        salesCategory: primaryKey,
        subGroups
      });
    });
    
    return result;
  } else if (groupBy === 'sectionSalesCategory') {
    // First group by Sales Category, then by Section within each category
    const primaryGrouped: { [key: string]: any[] } = {};
    
    items.forEach(item => {
      const salesCat = getItemField(item, 'salesCategory') || item.salesCategory || 'No Category';
      if (!primaryGrouped[salesCat]) {
        primaryGrouped[salesCat] = [];
      }
      primaryGrouped[salesCat].push(item);
    });
    
    // Sort primary groups alphabetically
    const sortedPrimaryKeys = Object.keys(primaryGrouped).sort();
    
    // Within each primary group, group by section and sort naturally (D, D01, DD2, DE1)
    const result: Array<{ salesCategory: string; subGroups: Array<{ key: string; items: any[] }> }> = [];
    sortedPrimaryKeys.forEach(primaryKey => {
      const secondaryGrouped: { [key: string]: any[] } = {};
      primaryGrouped[primaryKey].forEach(item => {
        const section = getItemField(item, 'section') || item.section || item.inventory?.Section || '';
        if (!secondaryGrouped[section]) {
          secondaryGrouped[section] = [];
        }
        secondaryGrouped[section].push(item);
      });
      
      // Sort sections naturally (D, D01, DD2, DE1)
      const sortedSections = Object.keys(secondaryGrouped).sort(naturalSort);
      const subGroups = sortedSections.map(section => ({
        key: section,
        items: secondaryGrouped[section].sort(sortByDescription)
      }));
      
      result.push({
        salesCategory: primaryKey,
        subGroups
      });
    });
    
    return result;
  } else if (groupBy === 'locationSalesCategory') {
    // First group by Sales Category, then by Location within each category
    const primaryGrouped: { [key: string]: any[] } = {};
    
    items.forEach(item => {
      const salesCat = getItemField(item, 'salesCategory') || item.salesCategory || 'No Category';
      if (!primaryGrouped[salesCat]) {
        primaryGrouped[salesCat] = [];
      }
      primaryGrouped[salesCat].push(item);
    });
    
    // Sort primary groups alphabetically
    const sortedPrimaryKeys = Object.keys(primaryGrouped).sort();
    
    // Within each primary group, group by location and sort numerically
    const result: Array<{ salesCategory: string; subGroups: Array<{ key: string; items: any[] }> }> = [];
    sortedPrimaryKeys.forEach(primaryKey => {
      const secondaryGrouped: { [key: string]: any[] } = {};
      primaryGrouped[primaryKey].forEach(item => {
        // Show "0" instead of "No Location" when location is empty or 0
        const locationValue = getItemField(item, 'location') || item.location || item.inventory?.Location;
        const location = locationValue && locationValue !== '' && locationValue !== 0 
          ? String(locationValue) 
          : '0';
        if (!secondaryGrouped[location]) {
          secondaryGrouped[location] = [];
        }
        secondaryGrouped[location].push(item);
      });
      
      // Sort locations numerically
      const sortedLocations = Object.keys(secondaryGrouped).sort((a, b) => {
        const aNum = parseFloat(a);
        const bNum = parseFloat(b);
        if (!isNaN(aNum) && !isNaN(bNum)) {
          return aNum - bNum;
        }
        return naturalSort(a, b);
      });
      const subGroups = sortedLocations.map(location => ({
        key: location,
        items: secondaryGrouped[location].sort(sortByDescription)
      }));
      
      result.push({
        salesCategory: primaryKey,
        subGroups
      });
    });
    
    return result;
  }
  
  // Simple grouping for other options
  const grouped: { [key: string]: any[] } = {};
  
  items.forEach(item => {
    let groupKey = '';
    
    if (groupBy === 'salesCategory') {
      groupKey = getItemField(item, 'salesCategory') || item.salesCategory || '';
    } else if (groupBy === 'priceClass') {
      groupKey = getItemField(item, 'priceClass') || item.priceClass || '';
    } else if (groupBy === 'section') {
      groupKey = getItemField(item, 'section') || item.section || item.inventory?.Section || '';
    } else if (groupBy === 'location') {
      // Show "0" instead of "No Location" when location is empty or 0
      const locationValue = getItemField(item, 'location') || item.location || item.inventory?.Location;
      groupKey = locationValue && locationValue !== '' && locationValue !== 0 
        ? String(locationValue) 
        : '0';
    } else if (groupBy === 'sequence') {
      const seqValue = getItemField(item, 'sequence') || item.sequence || item.inventory?.Sequence || 0;
      groupKey = String(seqValue);
    }
    
    if (!grouped[groupKey]) {
      grouped[groupKey] = [];
    }
    grouped[groupKey].push(item);
  });
  
  // Sort keys - numerical for location and sequence, natural for section, alphabetical for others
  const sortedKeys = Object.keys(grouped).sort((a, b) => {
    if (groupBy === 'sequence' || groupBy === 'location') {
      // Numerical sort for sequence and location
      const aNum = parseFloat(a);
      const bNum = parseFloat(b);
      if (!isNaN(aNum) && !isNaN(bNum)) {
        return aNum - bNum;
      }
      return naturalSort(a, b);
    } else if (groupBy === 'section') {
      // Natural sort for section (D, D01, DD2, DE1)
      return naturalSort(a, b);
    }
    // Alphabetical for others
    return a.localeCompare(b);
  });
  
  return sortedKeys.map(key => ({
    key,
    items: grouped[key].sort(sortByDescription)
  }));
};

// Get template from API
const getTemplateFromAPI = async (): Promise<PicklistTemplate | null> => {
  try {
    const response: any = await getPicklistTemplate();
    const responseData = response?.data;
    
    // Handle new API response structure: { success, message, data: { picklists: [...] } }
    const picklists = responseData?.picklists || [];
    
    if (picklists.length === 0) {
      return null;
    }
    
    // Get the first (and only) template from the array
    const templateData = picklists[0];

    // Transform API response to PicklistTemplate format
    // Convert 'none' back to empty string for internal use (groupItems function expects empty string)
    const groupByValue = templateData.groupBy === 'none' ? '' : (templateData.groupBy || '');
    const template: PicklistTemplate = {
      id: String(templateData.id || 'default'),
      name: templateData.name || getTemplateName(groupByValue),
      selectedFields: templateData.selectedFields || {},
      groupBy: groupByValue,
      newCategoryOnNewPage: templateData.newCategoryOnNewPage || false,
      showSubHeader: templateData.showSubHeader !== undefined ? templateData.showSubHeader : false,
      headerPosition: templateData.headerPosition || 'topRight',
      footerPosition: templateData.footerPosition || 'left',
      pickedByPosition: templateData.pickedByPosition || 'top',
      checkedByPosition: templateData.checkedByPosition || 'top',
      showBarcode: templateData.showBarcode !== undefined ? templateData.showBarcode : true,
      showTotalCartons: templateData.showTotalCartons !== undefined ? templateData.showTotalCartons : true,
      showTotalPieces: templateData.showTotalPieces !== undefined ? templateData.showTotalPieces : true,
      showTotalLines: templateData.showTotalLines !== undefined ? templateData.showTotalLines : true,
      showPickedBy: templateData.showPickedBy !== undefined ? templateData.showPickedBy : true,
      showCheckedBy: templateData.showCheckedBy !== undefined ? templateData.showCheckedBy : true,
      showBundles: templateData.showBundles !== undefined ? templateData.showBundles : true,
      createdAt: templateData.createdAt || new Date().toISOString(),
      updatedAt: templateData.updatedAt || new Date().toISOString(),
    };

    return template;
  } catch (error) {
    console.error('Error loading template from API:', error);
    
    // Fallback to localStorage if API fails
    try {
      const stored = localStorage.getItem('picklist_templates');
      if (!stored) return null;
      const templates: PicklistTemplate[] = JSON.parse(stored);
      if (templates.length > 0) {
        return templates.sort((a, b) => 
          new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
        )[0];
      }
    } catch (localError) {
      console.error('Error loading template from localStorage:', localError);
    }
    
    return null;
  }
};

// Helper to generate template name from groupBy
const getTemplateName = (groupByValue: string): string => {
  if (!groupByValue) return '';
  const firstChar = groupByValue.charAt(0).toUpperCase();
  const rest = groupByValue.slice(1);
  return `temp${firstChar}${rest}`;
};

// Order data type used by picklist generator
export type PicklistOrderData = {
  customer: { number: number; name: string; address: string; route: number; stop: number };
  distributor: { name: string; address?: string };
  invoiceNumber: string;
  isReprint: boolean;
  orderNumber: string;
  orderDate: string;
  invoiceDate: string;
  items: Array<{
    lineNumber: number;
    orderedQty: number;
    itemNumber: number;
    description: string;
    pack: number;
    size: string;
    upc?: string;
    salesCategory?: string;
    priceClass?: string;
    section?: string;
    location?: string;
    vendorItem?: string;
    sequence?: number;
  }>;
  totals: { totalPieces: number; totalCartons: number; totalLines: number };
};

// Build picklist doc for one or more orders (each order starts on a new page). Returns doc and orderData per page for final header.
const buildPicklistDoc = async (
  orderDataArray: PicklistOrderData[],
): Promise<{ doc: jsPDF; pagesOrderData: PicklistOrderData[]; template: PicklistTemplate; logoDataUrl: string | null }> => {
  const template = await getTemplateFromAPI();
  if (!template) {
    throw new Error('No picklist template found. Please configure and save a template in Settings > Picklist Template.');
  }
  const logoDataUrl = await loadLogoAsDataUrl();
  const selectedFieldKeys = Object.keys(template.selectedFields)
    .filter(key => template.selectedFields[key] && FIELD_LABELS.hasOwnProperty(key));
  const totalFields = selectedFieldKeys.length;
  const hasSectionOrLocation = selectedFieldKeys.includes('section') || selectedFieldKeys.includes('location');
  const isLandscape = totalFields > 7 && !hasSectionOrLocation;
  const doc = new jsPDF(isLandscape ? 'landscape' : 'portrait', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  const headerMargin = 2;
  const pagesOrderData: PicklistOrderData[] = [];
  const autoTableFn = jspdfAutoTable.default || jspdfAutoTable.autoTable || jspdfAutoTable;
  const fixedOrder = ['lineNumber', 'orderedQty', 'scannedQty', 'description', 'itemNumber', 'pack', 'size'];
  const finalFieldKeys: string[] = [];
  fixedOrder.forEach(key => {
    if (selectedFieldKeys.includes(key)) finalFieldKeys.push(key);
  });
  selectedFieldKeys.forEach(key => {
    if (!fixedOrder.includes(key)) finalFieldKeys.push(key);
  });
  const headerLabels = finalFieldKeys.map(key => FIELD_LABELS[key] || key);

  for (let orderIndex = 0; orderIndex < orderDataArray.length; orderIndex++) {
    const orderData = orderDataArray[orderIndex];
    if (orderIndex > 0) {
      doc.addPage('a4', isLandscape ? 'landscape' : 'portrait');
    }
    (pagesOrderData as any)[doc.getNumberOfPages() - 1] = orderData;

    const headerHeight = addFullHeaderToPage(doc, 1, 1, orderData, template);
    let yPosition = headerHeight + headerMargin;
    const grouped = groupItems(orderData.items, template.groupBy);
    const isNestedStructure = grouped.length > 0 && 'salesCategory' in grouped[0] && 'subGroups' in grouped[0];
  
  if (isNestedStructure) {
    // Handle nested structure: Sales Category -> Section/Location/Sequence
    (grouped as Array<{ salesCategory: string; subGroups: Array<{ key: string; items: any[] }> }>).forEach((categoryGroup, categoryIndex) => {
      // Check if we need a new page for new category
      if (template.newCategoryOnNewPage && categoryIndex > 0) {
        doc.addPage();
        (pagesOrderData as any)[doc.getNumberOfPages() - 1] = orderData;
        yPosition = headerHeight + headerMargin;
      }
      
      // Add spacing before new category (except first one, and skip if new category on new page)
      if (categoryIndex > 0 && !template.newCategoryOnNewPage) {
        yPosition += 4;
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.3);
        doc.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
        yPosition += 4;
      }
      
      // Sales Category header - only when showSubHeader is enabled (default: hidden to use space for rows)
      if (template.showSubHeader) {
        const categoryBoxHeight = 6;
        doc.setFillColor(240, 245, 250);
        doc.setDrawColor(200, 210, 220);
        doc.setLineWidth(0.3);
        doc.roundedRect(margin, yPosition - 4, pageWidth - (margin * 2), categoryBoxHeight, 1.5, 1.5, 'FD');
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 50, 80);
        doc.text('Sales Category:', margin + 3, yPosition);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        const categoryLabelWidth = doc.getTextWidth('Sales Category:');
        doc.text(categoryGroup.salesCategory, margin + 3 + categoryLabelWidth + 2, yPosition);
        yPosition += 7;
      }
      
      // Sub-groups (Section/Location/Sequence) - visually distinct with indentation
      categoryGroup.subGroups.forEach((subGroup, subIndex) => {
        // Add small spacing between sub-groups
        if (subIndex > 0) {
          yPosition += 2;
        }
        
        // Sub-group header with indentation and subtle background
        const subBoxHeight = 5;
        doc.setFillColor(250, 252, 255);
        doc.setDrawColor(220, 225, 230);
        doc.setLineWidth(0.2);
        doc.roundedRect(margin + 3, yPosition - 3.5, pageWidth - (margin * 2) - 6, subBoxHeight, 1, 1, 'FD');
        
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(50, 70, 100);
        
        let subLabel = '';
        if (template.groupBy === 'sequenceSalesCategory') {
          subLabel = 'Sequence:';
        } else if (template.groupBy === 'sectionSalesCategory') {
          subLabel = 'Section:';
        } else if (template.groupBy === 'locationSalesCategory') {
          subLabel = 'Location:';
        }
        
        doc.text(subLabel, margin + 6, yPosition);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(0, 0, 0);
        const subLabelWidth = doc.getTextWidth(subLabel);
        doc.text(subGroup.key, margin + 6 + subLabelWidth + 2, yPosition);
        yPosition += 5.5;
        
        // Table data - use finalFieldKeys to match column order
        const tableData = subGroup.items.map(item => 
          finalFieldKeys.map(key => {
            // Use helper function to get value (handles both direct and nested inventory properties)
            const value = getItemField(item, key) || (item as any)[key];
            // Handle different value types properly
            if (value === null || value === undefined) {
              return '-';
            }
            // For numbers, convert to string with proper formatting
            if (typeof value === 'number') {
              // For quantities, show as integer if whole number, otherwise show decimals
              if (key === 'orderedQty' || key === 'pack' || key === 'lineNumber' || key === 'sequence') {
                return value % 1 === 0 ? String(Math.round(value)) : String(value);
              }
              return String(value);
            }
            // For strings, return as is (empty string is valid for scannedQty)
            return String(value);
          })
        );
        
        autoTableFn(doc, {
          head: [headerLabels],
          body: tableData,
          startY: yPosition,
          styles: { 
            fontSize: 7, 
            cellPadding: 1.5,
            lineColor: [200, 200, 200],
            lineWidth: 0.1,
          },
          headStyles: { 
            fillColor: [240, 240, 240], 
            textColor: [0, 0, 0], 
            fontStyle: 'normal',
            fontSize: 7,
          },
          margin: { top: headerHeight + headerMargin, left: margin, right: margin, bottom: 40 },
          didDrawPage: () => {
            (pagesOrderData as any)[doc.getNumberOfPages() - 1] = orderData;
            addFooterToPage(doc, logoDataUrl || undefined, template.footerPosition);
            const currentPage = doc.getNumberOfPages();
            addFullHeaderToPage(doc, currentPage, doc.getNumberOfPages(), orderData, template);
          },
        });
        
        yPosition = (doc as any).lastAutoTable.finalY + 5;
      });
    });
  } else {
    // Handle simple structure (non-nested)
    (grouped as Array<{ key: string; items: any[] }>).forEach((group, groupIndex) => {
      // Check if we need a new page for new category
      const isSalesCategoryGrouping = template.groupBy === 'salesCategory' || 
                                      template.groupBy === 'sectionSalesCategory' || 
                                      template.groupBy === 'locationSalesCategory' || 
                                      template.groupBy === 'sequenceSalesCategory';
      if (template.newCategoryOnNewPage && isSalesCategoryGrouping && groupIndex > 0) {
        doc.addPage();
        (pagesOrderData as any)[doc.getNumberOfPages() - 1] = orderData;
        yPosition = headerHeight + headerMargin;
      }
      
      // Add divider before new group (except first one, and skip if new category on new page)
      if (groupIndex > 0 && !(template.newCategoryOnNewPage && isSalesCategoryGrouping)) {
        doc.setDrawColor(0, 0, 0); // Black
        doc.setLineWidth(0.3);
        doc.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
        yPosition += 3;
      }
      
      // Group header - only when showSubHeader is enabled (default: hidden to use space for rows)
      if (template.showSubHeader && template.groupBy) {
        const groupBoxHeight = 6;
        doc.setFillColor(240, 245, 250);
        doc.setDrawColor(200, 210, 220);
        doc.setLineWidth(0.3);
        doc.roundedRect(margin, yPosition - 4, pageWidth - (margin * 2), groupBoxHeight, 1.5, 1.5, 'FD');
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 50, 80);
        
        let label = '';
        if (template.groupBy === 'salesCategory') {
          label = 'Sales Category:';
        } else if (template.groupBy === 'priceClass') {
          label = 'Price Class:';
        } else if (template.groupBy === 'section') {
          label = 'Section:';
        } else if (template.groupBy === 'location') {
          label = 'Location:';
        } else if (template.groupBy === 'sequence') {
          label = 'Sequence:';
        }
        
        doc.text(label, margin + 3, yPosition);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        const labelWidth = doc.getTextWidth(label);
        doc.text(group.key, margin + 3 + labelWidth + 2, yPosition);
        yPosition += 7;
      }
      
      // Table data - use finalFieldKeys to match column order
      const tableData = group.items.map(item => 
        finalFieldKeys.map(key => {
          // Use helper function to get value (handles both direct and nested inventory properties)
          const value = getItemField(item, key) || (item as any)[key];
          // Handle different value types properly
          if (value === null || value === undefined) {
            return '-';
          }
          // For numbers, convert to string with proper formatting
          if (typeof value === 'number') {
            // For quantities, show as integer if whole number, otherwise show decimals
            if (key === 'orderedQty' || key === 'pack' || key === 'lineNumber' || key === 'sequence') {
              return value % 1 === 0 ? String(Math.round(value)) : String(value);
            }
            // For prices/costs, show 2 decimal places
            // (removed unitCost, extendedCost, retail fields)
            return String(value);
          }
          // For strings, return as is (empty string is valid for scannedQty)
          return String(value);
        })
      );
      
      autoTableFn(doc, {
        head: [headerLabels],
        body: tableData,
        startY: yPosition,
        styles: { 
          fontSize: 7, 
          cellPadding: 1.5,
          lineColor: [200, 200, 200],
          lineWidth: 0.1,
        },
        headStyles: { 
          fillColor: [240, 240, 240], 
          textColor: [0, 0, 0], 
          fontStyle: 'normal',
          fontSize: 7,
        },
        margin: { top: headerHeight + headerMargin, left: margin, right: margin, bottom: 40 },
        didDrawPage: () => {
          (pagesOrderData as any)[doc.getNumberOfPages() - 1] = orderData;
          addFooterToPage(doc, logoDataUrl || undefined, template.footerPosition);
          const currentPage = doc.getNumberOfPages();
          addFullHeaderToPage(doc, currentPage, doc.getNumberOfPages(), orderData, template);
        },
      });
      
      yPosition = (doc as any).lastAutoTable.finalY + 5;
    });
  }
  
  // Totals section at bottom (on last page of this order) - ensure enough space above footer
  let currentPage = doc.getNumberOfPages();
  doc.setPage(currentPage);
  
  // Calculate totals section position - dynamically adjust based on enabled footer items
  // Calculate space needed: fill-in fields take 7mm, auto-filled fields take 5mm
  let spaceNeeded = 11; // Base space for footer text + margin
  if (template.showPickedBy !== false && template.pickedByPosition === 'bottom') spaceNeeded += 7;
  if (template.showCheckedBy !== false && template.checkedByPosition === 'bottom') spaceNeeded += 7;
  if (template.showBundles !== false) spaceNeeded += 7;
  if (template.showTotalCartons !== false) spaceNeeded += 7; // Fill-in-the-blank
  if (template.showTotalPieces !== false) spaceNeeded += 7; // Fill-in-the-blank
  if (template.showTotalLines !== false) spaceNeeded += 5; // Auto-filled
  const totalsY = pageHeight - spaceNeeded;
  
  // Check if we need a new page for totals section
  // We need at least 10mm gap between last content and divider
  const minGapBeforeTotals = 10;
  const dividerY = totalsY - 6;
  const requiredYForDivider = dividerY - minGapBeforeTotals;
  
  // Get the last Y position from the last table
  const lastTableY = (doc as any).lastAutoTable?.finalY || yPosition;
  
  // If last content is too close to totals section, add a new page
  if (lastTableY > requiredYForDivider) {
    doc.addPage();
    (pagesOrderData as any)[doc.getNumberOfPages() - 1] = orderData;
    currentPage = doc.getNumberOfPages();
    doc.setPage(currentPage);
    yPosition = headerHeight + headerMargin;
  }
  
  // Ensure we're on the correct page before adding totals
  doc.setPage(currentPage);
  
  // Add divider above footer/totals section (with more gap before totals)
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.3);
  doc.line(margin, dividerY, pageWidth - margin, dividerY);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  
  // Left side: Fill-in fields (Picked by, Checked by, Bundles)
  let leftYPos = totalsY;
  if (template.pickedByPosition === 'bottom' && template.showPickedBy !== false) {
    doc.text('Picked by:', margin, leftYPos);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin + 25, leftYPos + 2, margin + 60, leftYPos + 2);
    leftYPos += 7;
  }
  if (template.checkedByPosition === 'bottom' && template.showCheckedBy !== false) {
    doc.text('Checked by:', margin, leftYPos);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin + 30, leftYPos + 2, margin + 65, leftYPos + 2);
    leftYPos += 7;
  }
  if (template.showBundles !== false) {
    doc.text('Bundles:', margin, leftYPos);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin + 25, leftYPos + 2, margin + 60, leftYPos + 2);
    leftYPos += 7;
  }
  
  let rightYPos = totalsY;
  if (template.showTotalCartons !== false) {
    const labelText = 'Total Cartons:';
    const labelWidth = doc.getTextWidth(labelText);
    const labelX = pageWidth - margin - 40;
    doc.text(labelText, labelX, rightYPos);
    doc.setDrawColor(200, 200, 200);
    doc.line(labelX + labelWidth + 2, rightYPos + 2, pageWidth - margin, rightYPos + 2);
    rightYPos += 7;
  }
  if (template.showTotalPieces !== false) {
    const labelText = 'Total Pieces:';
    const labelWidth = doc.getTextWidth(labelText);
    const labelX = pageWidth - margin - 40;
    doc.text(labelText, labelX, rightYPos);
    doc.setDrawColor(200, 200, 200);
    doc.line(labelX + labelWidth + 2, rightYPos + 2, pageWidth - margin, rightYPos + 2);
    rightYPos += 7;
  }
  if (template.showTotalLines !== false) {
    const labelX = pageWidth - margin - 40;
    doc.text(`Total Lines: ${orderData.totals.totalLines}`, labelX, rightYPos);
    rightYPos += 5;
  }
  } // end for each order

  return { doc, pagesOrderData, template, logoDataUrl };
};

const finalizeAndOpenPicklistDoc = (
  doc: jsPDF,
  pagesOrderData: PicklistOrderData[],
  template: PicklistTemplate,
  logoDataUrl: string | null,
  openAsPrint: boolean = true,
  filename?: string,
) => {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooterToPage(doc, logoDataUrl || undefined, template.footerPosition);
    const orderDataForPage = (pagesOrderData as any)[i - 1];
    addFullHeaderToPage(doc, i, totalPages, orderDataForPage || pagesOrderData[0], template);
  }
  const pdfBlob = doc.output('blob');
  const pdfUrl = URL.createObjectURL(pdfBlob);
  const printWindow = window.open(pdfUrl, '_blank');
  if (printWindow && openAsPrint) {
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        URL.revokeObjectURL(pdfUrl);
      }, 250);
    };
  } else if (!openAsPrint && filename) {
    doc.save(filename);
  } else if (!printWindow) {
    const first = pagesOrderData[0];
    doc.save(first ? `picklist-${first.orderNumber}.pdf` : 'picklist-bulk.pdf');
  }
};

// Generate Picklist PDF (single order)
export const generatePicklistPDF = async (orderData: PicklistOrderData): Promise<void> => {
  const { doc, pagesOrderData, template, logoDataUrl } = await buildPicklistDoc([orderData]);
  finalizeAndOpenPicklistDoc(doc, pagesOrderData, template, logoDataUrl, true);
};

// Generate combined bulk picklist PDF (multiple orders in one doc, each order starts on a new page)
export const generateBulkPicklistPDF = async (orderDataArray: PicklistOrderData[]): Promise<void> => {
  if (!orderDataArray || orderDataArray.length === 0) {
    throw new Error('No orders selected for bulk picklist.');
  }
  const { doc, pagesOrderData, template, logoDataUrl } = await buildPicklistDoc(orderDataArray);
  finalizeAndOpenPicklistDoc(doc, pagesOrderData, template, logoDataUrl, true);
};


