import jsPDF from 'jspdf';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const jspdfAutoTable = require('jspdf-autotable');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const JsBarcode = require('jsbarcode');
// eslint-disable-next-line @typescript-eslint/no-require-imports
import rabbitLogo from '../assets/Rabbit.svg';
import { getPicklistTemplate } from '../redux/apis/distrubutor/settingApis';

// Template interface (same as in PicklistTemplateTab)
interface PicklistTemplate {
  id: string;
  name: string;
  selectedFields: { [key: string]: boolean };
  groupBy: 'salesCategory' | 'priceClass' | 'section' | 'location' | 'sectionSalesCategory' | 'locationSalesCategory' | 'sequence' | 'sequenceSalesCategory' | '';
  newCategoryOnNewPage: boolean;
  headerPosition: 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight';
  footerPosition: 'left' | 'right';
  pickedByPosition: 'top' | 'bottom';
  checkedByPosition: 'top' | 'bottom';
  // Header options
  showBarcode?: boolean;
  // Footer options - all configurable
  showTotalCartons?: boolean;
  showTotalPieces?: boolean;
  showTotalLines?: boolean;
  showPickedBy?: boolean;
  showCheckedBy?: boolean;
  showBundles?: boolean;
  createdAt: string;
  updatedAt: string;
}

// Field labels mapping
const FIELD_LABELS: { [key: string]: string } = {
  lineNumber: 'Line #',
  orderedQty: 'Ord Qty',
  scannedQty: 'Qty',
  itemNumber: 'Item Number',
  description: 'Description',
  pack: 'Pack',
  size: 'Size',
  upc: 'UPC',
  onhand: 'On Hand',
  salesCategory: 'Sales Category',
  priceClass: 'Price Class',
  unitCost: 'Unit Cost',
  extendedCost: 'Extended Cost',
  retail: 'Retail',
  section: 'Section',
  location: 'Location',
  vendorItem: 'Vendor Item',
  sequence: 'Sequence',
};

// Generate barcode as data URL
const generateBarcodeDataUrl = (text: string): string | null => {
  try {
    const canvas = document.createElement('canvas');
    JsBarcode(canvas, text, {
      format: 'CODE128',
      width: 1.5,
      height: 30,
      displayValue: true,
      fontSize: 10,
      margin: 2,
    });
    return canvas.toDataURL('image/png');
  } catch (error) {
    console.error('Error generating barcode:', error);
    return null;
  }
};

// Load logo as data URL
const loadLogoAsDataUrl = async (): Promise<string | null> => {
  try {
    return new Promise<string | null>((resolve) => {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      
      img.onload = () => {
        try {
          const canvas = document.createElement('canvas');
          const ctx = canvas.getContext('2d');
          if (ctx) {
            canvas.width = img.width || 40;
            canvas.height = img.height || 33;
            ctx.drawImage(img, 0, 0);
            const dataUrl = canvas.toDataURL('image/png');
            resolve(dataUrl);
          } else {
            resolve(null);
          }
        } catch (error) {
          console.error('Error converting logo to canvas:', error);
          resolve(null);
        }
      };
      
      img.onerror = async () => {
        try {
          const logoPath = rabbitLogo;
          if (typeof rabbitLogo === 'string' && !rabbitLogo.startsWith('data:') && !rabbitLogo.startsWith('http')) {
            const response = await fetch(logoPath);
            if (response.ok) {
              const blob = await response.blob();
              const reader = new FileReader();
              reader.onloadend = () => {
                if (typeof reader.result === 'string') {
                  resolve(reader.result);
                } else {
                  resolve(null);
                }
              };
              reader.onerror = () => resolve(null);
              reader.readAsDataURL(blob);
              return;
            }
          }
          
          const publicResponse = await fetch('/Rabbit.svg');
          if (publicResponse.ok) {
            const blob = await publicResponse.blob();
            const reader = new FileReader();
            reader.onloadend = () => {
              if (typeof reader.result === 'string') {
                resolve(reader.result);
              } else {
                resolve(null);
              }
            };
            reader.onerror = () => resolve(null);
            reader.readAsDataURL(blob);
          } else {
            resolve(null);
          }
        } catch (fetchError) {
          console.error('Error fetching logo:', fetchError);
          resolve(null);
        }
      };
      
      if (typeof rabbitLogo === 'string') {
        img.src = rabbitLogo;
      } else {
        img.src = rabbitLogo as string;
      }
    });
  } catch (error) {
    console.error('Error loading logo:', error);
    return null;
  }
};

// Add footer to PDF - "Generated by Woopsa" centered at very bottom with proper margin
const addFooterToPage = (doc: jsPDF, logoDataUrl: string | undefined, _footerPosition: 'left' | 'right') => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // "Generated by Woopsa" text - centered at very bottom with margin
  const generatedByY = pageHeight - 5; // Very close to bottom, but with margin
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  const text = 'Picklist Generated by Woopsa';
  const textWidth = doc.getTextWidth(text);
  const textX = (pageWidth - textWidth) / 2; // Center horizontally
  
  doc.text(text, textX, generatedByY);
  
  // Logo next to text
  if (logoDataUrl) {
    try {
      const logoWidth = 4;
      const logoHeight = 4;
      const logoSpacing = 1.5;
      const logoX = textX + textWidth + logoSpacing;
      const logoY = generatedByY - 3.5;
      
      try {
        doc.addImage(logoDataUrl, 'PNG', logoX, logoY, logoWidth, logoHeight);
      } catch {
        try {
          doc.addImage(logoDataUrl, 'SVG', logoX, logoY, logoWidth, logoHeight);
        } catch {
          doc.addImage(logoDataUrl, logoX, logoY, logoWidth, logoHeight);
        }
      }
    } catch (error) {
      console.error('Error adding logo to PDF:', error);
    }
  }
};

// Add full header information to each page
const addFullHeaderToPage = (
  doc: jsPDF, 
  pageNum: number, 
  totalPages: number,
  orderData: any,
  template: PicklistTemplate
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 10;
  const headerStartY = 8;
  let yPos = headerStartY + 4;
  
  // Page number at top right (above header box)
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const pageText = `Page ${pageNum} of ${totalPages}`;
  const textWidth = doc.getTextWidth(pageText);
  doc.text(pageText, pageWidth - margin - textWidth, 6);
  
  // Calculate column widths (3 columns: left, middle, right)
  const leftColumnWidth = (pageWidth - (margin * 2)) * 0.35; // 35% for customer info
  const middleColumnWidth = (pageWidth - (margin * 2)) * 0.30; // 30% for barcode
  const leftX = margin + 2;
  const middleX = margin + leftColumnWidth + 5;
  const rightX = pageWidth - margin - 2;
  
  // Calculate header height first
  let rightYPos = yPos;
  let rightContentHeight = 0;
  
  // Right side content height calculation
  rightContentHeight += 4; // Date
  rightContentHeight += 3.5; // Doc
  rightContentHeight += 3.5; // Order
  rightContentHeight += 3.5; // Distributor
  if (orderData.isReprint) rightContentHeight += 4;
  if (template.pickedByPosition === 'top' && template.showPickedBy !== false) rightContentHeight += 5;
  if (template.checkedByPosition === 'top' && template.showCheckedBy !== false) rightContentHeight += 5;
  
  const leftContentHeight = 4 + 3.5 + 3.5 + 3.5 + 3.5 + 3.5; // Label + 5 lines of customer info
  const middleContentHeight = 35; // Barcode height
  const headerBoxHeight = Math.max(leftContentHeight, rightContentHeight, middleContentHeight) + 8;
  
  // Draw header background box (no border)
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, headerStartY, pageWidth - (margin * 2), headerBoxHeight, 1, 1, 'F');
  
  // Main title - PICKLIST (bold, larger) - Left column
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('PICKLIST', leftX, yPos);
  
  // Middle column: Barcode of order number (doc number)
  const orderNumber = String(orderData.orderNumber || orderData.invoiceNumber || '');
  if (template.showBarcode !== false && orderNumber) {
    const barcodeDataUrl = generateBarcodeDataUrl(orderNumber);
    if (barcodeDataUrl) {
      try {
        const barcodeWidth = 25;
        const barcodeHeight = 15;
        const barcodeX = middleX + (middleColumnWidth - barcodeWidth) / 2;
        const barcodeY = yPos - 2;
        doc.addImage(barcodeDataUrl, 'PNG', barcodeX, barcodeY, barcodeWidth, barcodeHeight);
      } catch (error) {
        console.error('Error adding barcode to PDF:', error);
      }
    }
  }
  
  // Right side: Document information section
  rightYPos = yPos;
  
  // Date
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Date:', rightX - 35, rightYPos, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.invoiceDate || orderData.orderDate || ''), rightX, rightYPos, { align: 'right' });
  
  rightYPos += 3.8;
  // Doc Number
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Doc:', rightX - 35, rightYPos, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.invoiceNumber || ''), rightX, rightYPos, { align: 'right' });
  
  rightYPos += 3.8;
  // Order Number
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Order:', rightX - 35, rightYPos, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.orderNumber || ''), rightX, rightYPos, { align: 'right' });
  
  rightYPos += 3.8;
  // Distributor
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Distributor:', rightX - 35, rightYPos, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(7);
  doc.text(orderData.distributor.name, rightX, rightYPos, { align: 'right' });
  
  rightYPos += 4.5;
  // REPRINT badge
  if (orderData.isReprint) {
    doc.setFillColor(255, 240, 240);
    doc.setDrawColor(220, 0, 0);
    doc.setLineWidth(0.3);
    const reprintWidth = 20;
    const reprintX = rightX - reprintWidth;
    doc.roundedRect(reprintX, rightYPos - 3, reprintWidth, 4, 1, 1, 'FD');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(200, 0, 0);
    doc.text('REPRINT', rightX - reprintWidth / 2, rightYPos, { align: 'center' });
    rightYPos += 5;
  }
  
  // Picked by and Checked by (right side, top position)
  if ((template.pickedByPosition === 'top' && template.showPickedBy !== false) || 
      (template.checkedByPosition === 'top' && template.showCheckedBy !== false)) {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    if (template.pickedByPosition === 'top' && template.showPickedBy !== false) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text('Picked by:', rightX - 35, rightYPos, { align: 'right' });
      doc.setDrawColor(180, 180, 180);
      doc.setLineWidth(0.2);
      doc.line(rightX - 30, rightYPos + 2, rightX, rightYPos + 2);
      rightYPos += 5;
    }
    if (template.checkedByPosition === 'top' && template.showCheckedBy !== false) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(60, 60, 60);
      doc.text('Checked by:', rightX - 35, rightYPos, { align: 'right' });
      doc.setDrawColor(180, 180, 180);
      doc.setLineWidth(0.2);
      doc.line(rightX - 30, rightYPos + 2, rightX, rightYPos + 2);
      rightYPos += 5;
    }
  }
  
  // Left side: Customer information section
  yPos += 5;
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Customer Information', leftX, yPos);
  
  yPos += 4.5;
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  
  // Customer details with labels
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('ID:', leftX, yPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.customer.number), leftX + 8, yPos);
  
  yPos += 3.5;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Name:', leftX, yPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(orderData.customer.name, leftX + 12, yPos);
  
  yPos += 3.5;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Address:', leftX, yPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(orderData.customer.address, leftX + 15, yPos);
  
  yPos += 3.5;
  if (orderData.customer.phone) {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text('Phone:', leftX, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);
    doc.text(orderData.customer.phone, leftX + 12, yPos);
    yPos += 3.5;
  }
  
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Route:', leftX, yPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.customer.route || ''), leftX + 12, yPos);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text('Stop:', leftX + 35, yPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.text(String(orderData.customer.stop), leftX + 42, yPos);
  
  // Calculate the bottom position
  
  // Add divider below header (dark color like footer)
  const dividerY = headerStartY + headerBoxHeight + 2;
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(margin, dividerY, pageWidth - margin, dividerY);
  
  // Return the bottom position of header for table positioning
  return dividerY + 4; // Divider + spacing
};

// Natural/alphanumeric sort function for mixed alphanumeric strings (e.g., D, D01, DD2, DE1)
const naturalSort = (a: string, b: string): number => {
  // If both are numeric, sort numerically
  const aNum = parseFloat(a);
  const bNum = parseFloat(b);
  if (!isNaN(aNum) && !isNaN(bNum)) {
    return aNum - bNum;
  }
  
  // Natural sort for alphanumeric strings
  const aParts = a.match(/(\d+|\D+)/g) || [];
  const bParts = b.match(/(\d+|\D+)/g) || [];
  const maxLength = Math.max(aParts.length, bParts.length);
  
  for (let i = 0; i < maxLength; i++) {
    const aPart = aParts[i] || '';
    const bPart = bParts[i] || '';
    
    const aIsNum = !isNaN(parseFloat(aPart));
    const bIsNum = !isNaN(parseFloat(bPart));
    
    if (aIsNum && bIsNum) {
      const diff = parseFloat(aPart) - parseFloat(bPart);
      if (diff !== 0) return diff;
    } else if (aIsNum) {
      return -1; // Numbers come before non-numbers
    } else if (bIsNum) {
      return 1; // Numbers come before non-numbers
    } else {
      const diff = aPart.localeCompare(bPart);
      if (diff !== 0) return diff;
    }
  }
  
  return 0;
};

// Group items based on selected grouping
const groupItems = (items: any[], groupBy: string) => {
  if (!groupBy) return [{ key: 'all', items }];
  
  // Handle hierarchical grouping (Sales Category first, then Section/Location/Sequence)
  if (groupBy === 'sequenceSalesCategory') {
    // First group by Sales Category, then by Sequence within each category
    const primaryGrouped: { [key: string]: any[] } = {};
    
    items.forEach(item => {
      const salesCat = item.salesCategory || 'No Category';
      if (!primaryGrouped[salesCat]) {
        primaryGrouped[salesCat] = [];
      }
      primaryGrouped[salesCat].push(item);
    });
    
    // Sort primary groups alphabetically
    const sortedPrimaryKeys = Object.keys(primaryGrouped).sort();
    
    // Within each primary group, group by sequence and sort numerically
    const result: Array<{ salesCategory: string; subGroups: Array<{ key: string; items: any[] }> }> = [];
    sortedPrimaryKeys.forEach(primaryKey => {
      const secondaryGrouped: { [key: string]: any[] } = {};
      primaryGrouped[primaryKey].forEach(item => {
        const seq = String(item.sequence || 0);
        if (!secondaryGrouped[seq]) {
          secondaryGrouped[seq] = [];
        }
        secondaryGrouped[seq].push(item);
      });
      
      // Sort sequences numerically
      const sortedSeqs = Object.keys(secondaryGrouped).sort((a, b) => parseInt(a) - parseInt(b));
      const subGroups = sortedSeqs.map(seq => ({
        key: seq,
        items: secondaryGrouped[seq]
      }));
      
      result.push({
        salesCategory: primaryKey,
        subGroups
      });
    });
    
    return result;
  } else if (groupBy === 'sectionSalesCategory') {
    // First group by Sales Category, then by Section within each category
    const primaryGrouped: { [key: string]: any[] } = {};
    
    items.forEach(item => {
      const salesCat = item.salesCategory || 'No Category';
      if (!primaryGrouped[salesCat]) {
        primaryGrouped[salesCat] = [];
      }
      primaryGrouped[salesCat].push(item);
    });
    
    // Sort primary groups alphabetically
    const sortedPrimaryKeys = Object.keys(primaryGrouped).sort();
    
    // Within each primary group, group by section and sort naturally (D, D01, DD2, DE1)
    const result: Array<{ salesCategory: string; subGroups: Array<{ key: string; items: any[] }> }> = [];
    sortedPrimaryKeys.forEach(primaryKey => {
      const secondaryGrouped: { [key: string]: any[] } = {};
      primaryGrouped[primaryKey].forEach(item => {
        const section = item.section || '';
        if (!secondaryGrouped[section]) {
          secondaryGrouped[section] = [];
        }
        secondaryGrouped[section].push(item);
      });
      
      // Sort sections naturally (D, D01, DD2, DE1)
      const sortedSections = Object.keys(secondaryGrouped).sort(naturalSort);
      const subGroups = sortedSections.map(section => ({
        key: section,
        items: secondaryGrouped[section]
      }));
      
      result.push({
        salesCategory: primaryKey,
        subGroups
      });
    });
    
    return result;
  } else if (groupBy === 'locationSalesCategory') {
    // First group by Sales Category, then by Location within each category
    const primaryGrouped: { [key: string]: any[] } = {};
    
    items.forEach(item => {
      const salesCat = item.salesCategory || 'No Category';
      if (!primaryGrouped[salesCat]) {
        primaryGrouped[salesCat] = [];
      }
      primaryGrouped[salesCat].push(item);
    });
    
    // Sort primary groups alphabetically
    const sortedPrimaryKeys = Object.keys(primaryGrouped).sort();
    
    // Within each primary group, group by location and sort numerically
    const result: Array<{ salesCategory: string; subGroups: Array<{ key: string; items: any[] }> }> = [];
    sortedPrimaryKeys.forEach(primaryKey => {
      const secondaryGrouped: { [key: string]: any[] } = {};
      primaryGrouped[primaryKey].forEach(item => {
        // Show "0" instead of "No Location" when location is empty or 0
        const location = item.location && item.location !== '' ? String(item.location) : '0';
        if (!secondaryGrouped[location]) {
          secondaryGrouped[location] = [];
        }
        secondaryGrouped[location].push(item);
      });
      
      // Sort locations numerically
      const sortedLocations = Object.keys(secondaryGrouped).sort((a, b) => {
        const aNum = parseFloat(a);
        const bNum = parseFloat(b);
        if (!isNaN(aNum) && !isNaN(bNum)) {
          return aNum - bNum;
        }
        return naturalSort(a, b);
      });
      const subGroups = sortedLocations.map(location => ({
        key: location,
        items: secondaryGrouped[location]
      }));
      
      result.push({
        salesCategory: primaryKey,
        subGroups
      });
    });
    
    return result;
  }
  
  // Simple grouping for other options
  const grouped: { [key: string]: any[] } = {};
  
  items.forEach(item => {
    let groupKey = '';
    
    if (groupBy === 'salesCategory') {
      groupKey = item.salesCategory || '';
    } else if (groupBy === 'priceClass') {
      groupKey = item.priceClass || '';
    } else if (groupBy === 'section') {
      groupKey = item.section || '';
    } else if (groupBy === 'location') {
      // Show "0" instead of "No Location" when location is empty or 0
      groupKey = item.location && item.location !== '' ? String(item.location) : '0';
    } else if (groupBy === 'sequence') {
      groupKey = String(item.sequence || 0);
    }
    
    if (!grouped[groupKey]) {
      grouped[groupKey] = [];
    }
    grouped[groupKey].push(item);
  });
  
  // Sort keys - numerical for location and sequence, natural for section, alphabetical for others
  const sortedKeys = Object.keys(grouped).sort((a, b) => {
    if (groupBy === 'sequence' || groupBy === 'location') {
      // Numerical sort for sequence and location
      const aNum = parseFloat(a);
      const bNum = parseFloat(b);
      if (!isNaN(aNum) && !isNaN(bNum)) {
        return aNum - bNum;
      }
      return naturalSort(a, b);
    } else if (groupBy === 'section') {
      // Natural sort for section (D, D01, DD2, DE1)
      return naturalSort(a, b);
    }
    // Alphabetical for others
    return a.localeCompare(b);
  });
  
  return sortedKeys.map(key => ({
    key,
    items: grouped[key]
  }));
};

// Get template from API
const getTemplateFromAPI = async (): Promise<PicklistTemplate | null> => {
  try {
    const response: any = await getPicklistTemplate();
    const responseData = response?.data;
    
    // Handle new API response structure: { success, message, data: { picklists: [...] } }
    const picklists = responseData?.picklists || [];
    
    if (picklists.length === 0) {
      return null;
    }
    
    // Get the first (and only) template from the array
    const templateData = picklists[0];

    // Transform API response to PicklistTemplate format
    const template: PicklistTemplate = {
      id: String(templateData.id || 'default'),
      name: templateData.name || getTemplateName(templateData.groupBy || ''),
      selectedFields: templateData.selectedFields || {},
      groupBy: templateData.groupBy || '',
      newCategoryOnNewPage: templateData.newCategoryOnNewPage || false,
      headerPosition: templateData.headerPosition || 'topRight',
      footerPosition: templateData.footerPosition || 'left',
      pickedByPosition: templateData.pickedByPosition || 'top',
      checkedByPosition: templateData.checkedByPosition || 'top',
      showBarcode: templateData.showBarcode !== undefined ? templateData.showBarcode : true,
      showTotalCartons: templateData.showTotalCartons !== undefined ? templateData.showTotalCartons : true,
      showTotalPieces: templateData.showTotalPieces !== undefined ? templateData.showTotalPieces : true,
      showTotalLines: templateData.showTotalLines !== undefined ? templateData.showTotalLines : true,
      showPickedBy: templateData.showPickedBy !== undefined ? templateData.showPickedBy : true,
      showCheckedBy: templateData.showCheckedBy !== undefined ? templateData.showCheckedBy : true,
      showBundles: templateData.showBundles !== undefined ? templateData.showBundles : true,
      createdAt: templateData.createdAt || new Date().toISOString(),
      updatedAt: templateData.updatedAt || new Date().toISOString(),
    };

    return template;
  } catch (error) {
    console.error('Error loading template from API:', error);
    
    // Fallback to localStorage if API fails
    try {
      const stored = localStorage.getItem('picklist_templates');
      if (!stored) return null;
      const templates: PicklistTemplate[] = JSON.parse(stored);
      if (templates.length > 0) {
        return templates.sort((a, b) => 
          new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
        )[0];
      }
    } catch (localError) {
      console.error('Error loading template from localStorage:', localError);
    }
    
    return null;
  }
};

// Helper to generate template name from groupBy
const getTemplateName = (groupByValue: string): string => {
  if (!groupByValue) return '';
  const firstChar = groupByValue.charAt(0).toUpperCase();
  const rest = groupByValue.slice(1);
  return `temp${firstChar}${rest}`;
};

// Generate Picklist PDF
export const generatePicklistPDF = async (
  orderData: {
    customer: {
      number: number;
      name: string;
      address: string;
      route: number;
      stop: number;
    };
    distributor: {
      name: string;
      address?: string;
    };
    invoiceNumber: string;
    isReprint: boolean;
    orderNumber: string;
    orderDate: string;
    invoiceDate: string;
    items: Array<{
      lineNumber: number;
      orderedQty: number;
      itemNumber: number;
      description: string;
      pack: number;
      size: string;
      upc?: string;
      onhand?: number;
      salesCategory?: string;
      priceClass?: string;
      unitCost?: number;
      extendedCost?: number;
      retail?: number;
      section?: string;
      location?: string;
      vendorItem?: string;
      sequence?: number;
    }>;
    totals: {
      totalPieces: number;
      totalCartons: number;
      totalLines: number;
      totalExtendedCost?: number;
    };
  },
): Promise<void> => {
  // Get template from API
  const template = await getTemplateFromAPI();
  
  if (!template) {
    throw new Error('No picklist template found. Please configure and save a template in Settings > Picklist Template.');
  }

  const logoDataUrl = await loadLogoAsDataUrl();
  const selectedFieldKeys = Object.keys(template.selectedFields).filter(key => template.selectedFields[key]);
  const totalFields = selectedFieldKeys.length;
  const isLandscape = totalFields > 7;
  
  const doc = new jsPDF(isLandscape ? 'landscape' : 'portrait', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  
  // Calculate header height dynamically
  // Header box starts at 8mm, with padding
  // Left side: Title (4) + Customer label (4.5) + Customer details (5 lines * 3.5) = ~26mm
  // Right side: Date/Doc/Order/Distributor (4 lines * 3.8) + REPRINT (5 if present) + Picked by/Checked by (0, 5, or 10mm)
  const leftSideHeight = 4 + 4.5 + (5 * 3.5); // ~26mm
  const rightSideBaseHeight = 4 + (4 * 3.8); // Date + Doc + Order + Distributor
  let rightSideHeight = rightSideBaseHeight;
  if (orderData.isReprint) rightSideHeight += 5;
  if (template.pickedByPosition === 'top' && template.showPickedBy !== false) rightSideHeight += 5;
  if (template.checkedByPosition === 'top' && template.showCheckedBy !== false) rightSideHeight += 5;
  
  const maxContentHeight = Math.max(leftSideHeight, rightSideHeight);
  const headerBoxHeight = maxContentHeight + 8; // Content + padding
  const headerHeight = 8 + headerBoxHeight + 2 + 4; // Start Y + box height + spacing + divider
  const headerMargin = 2;
  let yPosition = headerHeight + headerMargin; // Start below header with margin
  
  // Group items
  const grouped = groupItems(orderData.items, template.groupBy);
  
  // Fixed column sequence: lineNumber, orderedQty, scannedQty, description, itemNumber, pack, size, then others
  const fixedOrder = ['lineNumber', 'orderedQty', 'scannedQty', 'description', 'itemNumber', 'pack', 'size'];
  const finalFieldKeys: string[] = [];
  
  // First, add fixed order fields that are selected
  fixedOrder.forEach(key => {
    if (selectedFieldKeys.includes(key)) {
      finalFieldKeys.push(key);
    }
  });
  
  // Then add other selected fields in their original order
  selectedFieldKeys.forEach(key => {
    if (!fixedOrder.includes(key)) {
      finalFieldKeys.push(key);
    }
  });
  const headerLabels = finalFieldKeys.map(key => FIELD_LABELS[key] || key);
  
  const autoTableFn = jspdfAutoTable.default || jspdfAutoTable.autoTable || jspdfAutoTable;
  
  // Check if grouped has nested structure (for Sales Category combinations)
  const isNestedStructure = grouped.length > 0 && 'salesCategory' in grouped[0] && 'subGroups' in grouped[0];
  
  if (isNestedStructure) {
    // Handle nested structure: Sales Category -> Section/Location/Sequence
    (grouped as Array<{ salesCategory: string; subGroups: Array<{ key: string; items: any[] }> }>).forEach((categoryGroup, categoryIndex) => {
      // Check if we need a new page for new category
      if (template.newCategoryOnNewPage && categoryIndex > 0) {
        doc.addPage();
        yPosition = headerHeight + headerMargin;
      }
      
      // Add spacing before new category (except first one, and skip if new category on new page)
      if (categoryIndex > 0 && !template.newCategoryOnNewPage) {
        yPosition += 4;
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.3);
        doc.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
        yPosition += 4;
      }
      
      // Sales Category header - prominent with background box
      const categoryBoxHeight = 6;
      doc.setFillColor(240, 245, 250);
      doc.setDrawColor(200, 210, 220);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, yPosition - 4, pageWidth - (margin * 2), categoryBoxHeight, 1.5, 1.5, 'FD');
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 50, 80);
      doc.text('Sales Category:', margin + 3, yPosition);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      const categoryLabelWidth = doc.getTextWidth('Sales Category:');
      doc.text(categoryGroup.salesCategory, margin + 3 + categoryLabelWidth + 2, yPosition);
      yPosition += 7;
      
      // Sub-groups (Section/Location/Sequence) - visually distinct with indentation
      categoryGroup.subGroups.forEach((subGroup, subIndex) => {
        // Add small spacing between sub-groups
        if (subIndex > 0) {
          yPosition += 2;
        }
        
        // Sub-group header with indentation and subtle background
        const subBoxHeight = 5;
        doc.setFillColor(250, 252, 255);
        doc.setDrawColor(220, 225, 230);
        doc.setLineWidth(0.2);
        doc.roundedRect(margin + 3, yPosition - 3.5, pageWidth - (margin * 2) - 6, subBoxHeight, 1, 1, 'FD');
        
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(50, 70, 100);
        
        let subLabel = '';
        if (template.groupBy === 'sequenceSalesCategory') {
          subLabel = 'Sequence:';
        } else if (template.groupBy === 'sectionSalesCategory') {
          subLabel = 'Section:';
        } else if (template.groupBy === 'locationSalesCategory') {
          subLabel = 'Location:';
        }
        
        doc.text(subLabel, margin + 6, yPosition);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(0, 0, 0);
        const subLabelWidth = doc.getTextWidth(subLabel);
        doc.text(subGroup.key, margin + 6 + subLabelWidth + 2, yPosition);
        yPosition += 5.5;
        
        // Table data - use finalFieldKeys to match column order
        // Table data - use finalFieldKeys to match column order
        const tableData = subGroup.items.map(item => 
          finalFieldKeys.map(key => {
            const value = (item as any)[key];
            // Handle different value types properly
            if (value === null || value === undefined) {
              return '-';
            }
            // For numbers, convert to string with proper formatting
            if (typeof value === 'number') {
              // For quantities, show as integer if whole number, otherwise show decimals
              if (key === 'orderedQty' || key === 'pack' || key === 'onhand' || key === 'lineNumber' || key === 'sequence') {
                return value % 1 === 0 ? String(Math.round(value)) : String(value);
              }
              // For prices/costs, show 2 decimal places
              if (key === 'unitCost' || key === 'extendedCost' || key === 'retail') {
                return value.toFixed(2);
              }
              return String(value);
            }
            // For strings, return as is (empty string is valid for scannedQty)
            return String(value);
          })
        );
        
        autoTableFn(doc, {
          head: [headerLabels],
          body: tableData,
          startY: yPosition,
          styles: { 
            fontSize: 7, 
            cellPadding: 1.5,
            lineColor: [200, 200, 200],
            lineWidth: 0.1,
          },
          headStyles: { 
            fillColor: [240, 240, 240], 
            textColor: [0, 0, 0], 
            fontStyle: 'normal',
            fontSize: 7,
          },
          margin: { top: headerHeight + headerMargin, left: margin, right: margin, bottom: 40 },
          didDrawPage: () => {
            addFooterToPage(doc, logoDataUrl || undefined, template.footerPosition);
            const currentPage = doc.getNumberOfPages();
            const tempTotalPages = doc.getNumberOfPages();
            addFullHeaderToPage(doc, currentPage, tempTotalPages, orderData, template);
          },
        });
        
        yPosition = (doc as any).lastAutoTable.finalY + 5;
      });
    });
  } else {
    // Handle simple structure (non-nested)
    (grouped as Array<{ key: string; items: any[] }>).forEach((group, groupIndex) => {
      // Check if we need a new page for new category
      const isSalesCategoryGrouping = template.groupBy === 'salesCategory' || 
                                      template.groupBy === 'sectionSalesCategory' || 
                                      template.groupBy === 'locationSalesCategory' || 
                                      template.groupBy === 'sequenceSalesCategory';
      if (template.newCategoryOnNewPage && isSalesCategoryGrouping && groupIndex > 0) {
        doc.addPage();
        yPosition = headerHeight + headerMargin;
      }
      
      // Add divider before new group (except first one, and skip if new category on new page)
      if (groupIndex > 0 && !(template.newCategoryOnNewPage && isSalesCategoryGrouping)) {
        doc.setDrawColor(0, 0, 0); // Black
        doc.setLineWidth(0.3);
        doc.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
        yPosition += 3;
      }
      
      // Group header - prominent with background box
      if (template.groupBy) {
        const groupBoxHeight = 6;
        doc.setFillColor(240, 245, 250);
        doc.setDrawColor(200, 210, 220);
        doc.setLineWidth(0.3);
        doc.roundedRect(margin, yPosition - 4, pageWidth - (margin * 2), groupBoxHeight, 1.5, 1.5, 'FD');
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 50, 80);
        
        let label = '';
        if (template.groupBy === 'salesCategory') {
          label = 'Sales Category:';
        } else if (template.groupBy === 'priceClass') {
          label = 'Price Class:';
        } else if (template.groupBy === 'section') {
          label = 'Section:';
        } else if (template.groupBy === 'location') {
          label = 'Location:';
        } else if (template.groupBy === 'sequence') {
          label = 'Sequence:';
        }
        
        doc.text(label, margin + 3, yPosition);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);
        const labelWidth = doc.getTextWidth(label);
        doc.text(group.key, margin + 3 + labelWidth + 2, yPosition);
        yPosition += 7;
      }
      
      // Table data - use finalFieldKeys to match column order
      const tableData = group.items.map(item => 
        finalFieldKeys.map(key => {
          const value = (item as any)[key];
          // Handle different value types properly
          if (value === null || value === undefined) {
            return '-';
          }
          // For numbers, convert to string with proper formatting
          if (typeof value === 'number') {
            // For quantities, show as integer if whole number, otherwise show decimals
            if (key === 'orderedQty' || key === 'pack' || key === 'onhand' || key === 'lineNumber' || key === 'sequence') {
              return value % 1 === 0 ? String(Math.round(value)) : String(value);
            }
            // For prices/costs, show 2 decimal places
            if (key === 'unitCost' || key === 'extendedCost' || key === 'retail') {
              return value.toFixed(2);
            }
            return String(value);
          }
          // For strings, return as is (empty string is valid for scannedQty)
          return String(value);
        })
      );
      
      autoTableFn(doc, {
        head: [headerLabels],
        body: tableData,
        startY: yPosition,
        styles: { 
          fontSize: 7, 
          cellPadding: 1.5,
          lineColor: [200, 200, 200],
          lineWidth: 0.1,
        },
        headStyles: { 
          fillColor: [240, 240, 240], 
          textColor: [0, 0, 0], 
          fontStyle: 'normal',
          fontSize: 7,
        },
        margin: { top: headerHeight + headerMargin, left: margin, right: margin, bottom: 40 },
        didDrawPage: () => {
          addFooterToPage(doc, logoDataUrl || undefined, template.footerPosition);
          const currentPage = doc.getNumberOfPages();
          const tempTotalPages = doc.getNumberOfPages();
          addFullHeaderToPage(doc, currentPage, tempTotalPages, orderData, template);
        },
      });
      
      yPosition = (doc as any).lastAutoTable.finalY + 5;
    });
  }
  
  // Totals section at bottom (on last page only) - ensure enough space above footer
  const currentPage = doc.getNumberOfPages();
  doc.setPage(currentPage);
  
  // Calculate totals section position - dynamically adjust based on enabled footer items
  // Calculate space needed: fill-in fields take 7mm, auto-filled fields take 5mm
  let spaceNeeded = 11; // Base space for footer text + margin
  if (template.showPickedBy !== false && template.pickedByPosition === 'bottom') spaceNeeded += 7;
  if (template.showCheckedBy !== false && template.checkedByPosition === 'bottom') spaceNeeded += 7;
  if (template.showBundles !== false) spaceNeeded += 7;
  if (template.showTotalCartons !== false) spaceNeeded += 7; // Fill-in-the-blank
  if (template.showTotalPieces !== false) spaceNeeded += 7; // Fill-in-the-blank
  if (template.showTotalLines !== false) spaceNeeded += 5; // Auto-filled
  const totalsY = pageHeight - spaceNeeded;
  
  // Add divider above footer/totals section (with more gap before totals)
  const dividerY = totalsY - 6;
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.3);
  doc.line(margin, dividerY, pageWidth - margin, dividerY);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  
  // Left side: Fill-in fields (Picked by, Checked by, Bundles)
  let leftYPos = totalsY;
  if (template.pickedByPosition === 'bottom' && template.showPickedBy !== false) {
    doc.text('Picked by:', margin, leftYPos);
    // Add blank line for manual entry
    doc.setDrawColor(200, 200, 200);
    doc.line(margin + 25, leftYPos + 2, margin + 60, leftYPos + 2);
    leftYPos += 7;
  }
  if (template.checkedByPosition === 'bottom' && template.showCheckedBy !== false) {
    doc.text('Checked by:', margin, leftYPos);
    // Add blank line for manual entry
    doc.setDrawColor(200, 200, 200);
    doc.line(margin + 30, leftYPos + 2, margin + 65, leftYPos + 2);
    leftYPos += 7;
  }
  if (template.showBundles !== false) {
    doc.text('Bundles:', margin, leftYPos);
    // Add blank line for manual entry
    doc.setDrawColor(200, 200, 200);
    doc.line(margin + 25, leftYPos + 2, margin + 60, leftYPos + 2);
    leftYPos += 7;
  }
  
  // Right side: Total Cartons/Pieces/Lines - only if enabled (fill-in-the-blank)
  let rightYPos = totalsY;
  if (template.showTotalCartons !== false) {
    const labelText = 'Total Cartons:';
    const labelWidth = doc.getTextWidth(labelText);
    const labelX = pageWidth - margin - 40; // Position label to leave space for line
    doc.text(labelText, labelX, rightYPos);
    // Add blank line for manual entry (beside the label)
    doc.setDrawColor(200, 200, 200);
    doc.line(labelX + labelWidth + 2, rightYPos + 2, pageWidth - margin, rightYPos + 2);
    rightYPos += 7;
  }
  if (template.showTotalPieces !== false) {
    const labelText = 'Total Pieces:';
    const labelWidth = doc.getTextWidth(labelText);
    const labelX = pageWidth - margin - 40; // Position label to leave space for line
    doc.text(labelText, labelX, rightYPos);
    // Add blank line for manual entry (beside the label)
    doc.setDrawColor(200, 200, 200);
    doc.line(labelX + labelWidth + 2, rightYPos + 2, pageWidth - margin, rightYPos + 2);
    rightYPos += 7;
  }
  if (template.showTotalLines !== false) {
    const labelX = pageWidth - margin - 40; // Same starting position as other fields
    doc.text(`Total Lines: ${orderData.totals.totalLines}`, labelX, rightYPos);
    rightYPos += 5;
  }
  
  // Add footer and full header to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooterToPage(doc, logoDataUrl || undefined, template.footerPosition);
    addFullHeaderToPage(doc, i, totalPages, orderData, template);
  }
  
  // Save PDF
  const filename = `picklist-${orderData.orderNumber}-${orderData.invoiceNumber}.pdf`;
  doc.save(filename);
};


