import { z } from 'zod';

// Helper to allow both string and number input, parses to number
function numberOrStringNumber(minValue = 0, errorMsg = 'Must be a number and at least ' + minValue) {
  return z.coerce.number({
    required_error: errorMsg,
    invalid_type_error: 'Must be a number',
  }).min(minValue, errorMsg);
}

export const retailerSchema = z.object({
  C_Name: z.string().min(1, 'Customer Name is required'),
  C_CoName: z.string(),
  C_Address: z.string().min(1, 'Address is required'),
  Address_Type: numberOrStringNumber(0),
  C_City: z.string().min(1, 'City is required'),
  C_State: z.string().min(1, 'State is required'),
  C_Country: z.string(),
  C_Contact1: z.string(),
  C_Contact2: z.string(),
  C_Zip: z.string().min(1, 'Zip Code is required'),
  C_Phone: z.string(),
  C_Email: z.string().email('Invalid email address').or(z.literal('')),
  Jurisdiction_State: z.coerce.string(),
  Jurisdiction_County: z.coerce.string(),
  Jurisdiction_City: z.coerce.string(),
  C_Fax: z.string(),
  C_SalesTaxNumber: z.string(),
  C_CigtLicenseNumber: z.string(),
  C_Salesman: numberOrStringNumber(0),
  C_FEIN: z.string(),
  C_OperationHours1: numberOrStringNumber(0),
  C_OperationHours2: numberOrStringNumber(0),
  C_Inactive: numberOrStringNumber(0),
  C_StatusCode: numberOrStringNumber(0),
  Delivery_Charge: numberOrStringNumber(0),
  Delivery_Amount: numberOrStringNumber(0),
  C_CaseDiscount: numberOrStringNumber(0),
  C_OtherLicenseNumber: z.string(),
  C_OtherLicenseNumber2: z.string(),
  C_OtherLicenseNumber3: z.string(),
  C_OrderDay: numberOrStringNumber(0),
  C_RetailRounding: z.string(),
  C_ClassOfTrade: z.string(),
  C_InvoiceFormat: numberOrStringNumber(0),
  C_PricingAccount: numberOrStringNumber(0),
  Delivery_ID: numberOrStringNumber(0),
  C_SpecialTaxCode: z.string(),
  C_Memo: z.string(),
  PriceLevel_Default: numberOrStringNumber(0),
  EDI_Format: numberOrStringNumber(0),
  NetCost_Flag: z.boolean(),
  TermsCode: numberOrStringNumber(0),
  C_SalesTaxSelect: z.string().refine((val) => ['S', 'A', 'N'].includes(val), {
    message: 'Sales Tax Select must be S, A, or N'
  }),
  C_OrderDaySequence: numberOrStringNumber(0),
  Credit_Limit: numberOrStringNumber(0),
  C_DateCreatedUser: numberOrStringNumber(0),
  C_DateModifedUser: numberOrStringNumber(0),
  Service_Charge: numberOrStringNumber(0),
  Other_Amount: numberOrStringNumber(0),
  C_PhoneMobile: z.string(),
  POS_CashC: numberOrStringNumber(0),
  POS_CheckC: numberOrStringNumber(0),
  POS_CreditC: numberOrStringNumber(0),
  POS_DebitC: numberOrStringNumber(0),
  POS_OtherC: numberOrStringNumber(0),
  POS_HouseC: numberOrStringNumber(0),
  MSA_AcceptPromo: numberOrStringNumber(0),
  C_Alias: z.string(),
  emailInvoice: numberOrStringNumber(0),
  emailInvoiceEDI: numberOrStringNumber(0),
  emailReport: numberOrStringNumber(0),
  emailStatement: numberOrStringNumber(0),
  emailPromo: numberOrStringNumber(0),
  Category_Allow01: numberOrStringNumber(0),
  Category_Allow02: numberOrStringNumber(0),
  Category_Allow03: numberOrStringNumber(0),
  Category_Allow04: numberOrStringNumber(0),
  Category_Allow05: numberOrStringNumber(0),
  Category_Allow06: numberOrStringNumber(0),
  Category_Allow07: numberOrStringNumber(0),
  Category_Allow08: numberOrStringNumber(0),
  Category_Allow09: numberOrStringNumber(0),
  Category_Allow10: numberOrStringNumber(0),
  Category_Allow11: numberOrStringNumber(0),
  Category_Allow12: numberOrStringNumber(0),
});

export type RetailerFormData = z.infer<typeof retailerSchema>;

